Repository ColoredCow/portal, pull requests merged in 2018-08, with the labels that each got.

#641 ability to send calendar notification
  app/Services/CalendarEventService.php
Labels: HR, status : ready for review

#647 (#645) docblock corrections
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
Labels: status : ready to test

#650 template variable call from config
  app/Console/Commands/HR/ApplicationNoShow.php
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Mail/HR/Applicant/ScheduledInterviewReminder.php
  config/constants.php
Labels: status : development, status : ready for review

#656 (#588) removed some hard-coded routes
  resources/views/client/edit.blade.php
  resources/views/client/index.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/finance/menu.blade.php
  resources/views/finance/reports/report-table.blade.php
  resources/views/home.blade.php
  resources/views/knowledgecafe/index.blade.php
  routes/web.php
Labels: status : ready for review

#661 (#660) finance bug
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectStageController.php
  resources/assets/js/components/ProjectStageComponent.vue
Labels: status : ready for review
