Repository ColoredCow/portal, pull requests merged in 2018-05, with the labels that each got.

#145 (#82) invoice
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  database/migrations/2018_04_30_084508_invoice_cheque_dates.php
  resources/assets/js/app.js
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
Labels: status : ready for review

#149 (#62) show applicants for a job
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Requests/HR/ApplicantRequest.php
  resources/views/hr/job/index.blade.php
Labels: status : reviewed

#150 (#53) multiple emails
  app/Http/Controllers/ClientController.php
  app/Http/Requests/ClientRequest.php
  composer.json
  composer.lock
  database/migrations/2018_05_01_132524_update_client_emails_column.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/client/index.blade.php
Labels: Finance, status : ready for review

#108 (#82) invoice payment section
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/ProjectStageController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Http/Requests/ProjectRequest.php
  app/Models/Finance/Invoice.php
  app/Models/ProjectStage.php
  app/Models/ProjectStageBilling.php
  database/migrations/2018_05_02_121734_billing_invoices_many_to_one_mapping.php
  resources/assets/js/app.js
  resources/assets/js/components/InvoiceProjectComponent.vue
  resources/assets/js/components/InvoiceProjectSubComponent.vue
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
Labels: status : ready for review

#191 (#184) reports test feedback
  app/Http/Controllers/Finance/ReportsController.php
  app/Models/Finance/Invoice.php
  config/constants.php
  resources/assets/js/app.js
  resources/views/finance/reports/index.blade.php
Labels: Finance, status : ready for review

#201 (#200) Trial Program Round
  database/seeds/HRRoundsTrialProgramSeeder.php
Labels: HR, status : reviewed

#199 (#193) reporting details
  app/Helpers/DateHelper.php
  app/Http/Controllers/Finance/ReportsController.php
  app/Models/Finance/Invoice.php
  config/constants.php
  resources/assets/js/app.js
  resources/views/finance/menu.blade.php
  resources/views/finance/reports/index.blade.php
  resources/views/finance/reports/report-table.blade.php
Labels: status : reviewed

#194 (#192) ACL implementation (for CA)
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/Finance/ReportsController.php
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Controllers/HR/JobController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/SettingController.php
  app/Http/Controllers/WeeklyDoseController.php
  app/Http/Kernel.php
  app/Policies/ClientPolicy.php
  app/Policies/Finance/InvoicePolicy.php
  app/Policies/Finance/ReportPolicy.php
  app/Policies/HR/ApplicantPolicy.php
  app/Policies/HR/JobPolicy.php
  app/Policies/KnowledgeCafe/Library/BookPolicy.php
  app/Policies/ProjectPolicy.php
  app/Policies/SettingPolicy.php
  app/Policies/WeeklyDosePolicy.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  composer.json
  composer.lock
  config/app.php
  config/permission.php
  database/migrations/2018_05_09_155847_create_permission_tables.php
  database/seeds/PermissionsTableSeeder.php
  database/seeds/RoleHasPermissionsTableSeeder.php
  database/seeds/RolesTableSeeder.php
  resources/views/auth/login.blade.php
  resources/views/finance/menu.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: status : ready for review

#218 links correction. fixes #217
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
Labels: Finance, status : ready for review

#210 (#204) applicant application
  app/Events/HR/ApplicationCreated.php
  app/Http/Controllers/HR/ApplicationController.php
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Http/Controllers/HR/JobController.php
  app/Listeners/HR/AutoRespondApplicant.php
  app/Listeners/HR/CreateFirstApplicantRound.php
  app/Listeners/HR/CreateFirstApplicationRound.php
  app/Mail/HR/Applicant/RoundReviewed.php
  app/Models/HR/Applicant.php
  app/Models/HR/ApplicantReview.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationReview.php
  app/Models/HR/ApplicationRound.php
  app/Models/HR/Job.php
  app/Providers/EventServiceProvider.php
  database/migrations/2018_05_14_083216_create_hr_applications_table.php
  database/migrations/2018_05_14_144056_move_applicant_to_application_tables.php
  database/seeds/MigrateApplicantJobReferenceSeeder.php
  resources/views/home.blade.php
  resources/views/hr/applicant/index.blade.php
  resources/views/hr/applicant/timeline.blade.php
  resources/views/hr/application/auto-respond.blade.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/timeline.blade.php
  resources/views/hr/job/index.blade.php
  resources/views/hr/menu.blade.php
  resources/views/hr/round-review-mail-modal.blade.php
  resources/views/hr/round-review-sent-mail-modal.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: HR, status : reviewed

#224 (#223) and (#214)
  resources/views/hr/application/edit.blade.php
Labels: status : ready for review

#222 (#204) applicant changes
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Controllers/HR/ApplicationController.php
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Http/Requests/HR/ApplicationRoundRequest.php
  app/Listeners/HR/CreateFirstApplicationRound.php
  app/Models/HR/Applicant.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationRound.php
  config/constants.php
  database/migrations/2018_05_16_083123_dropapplicantcolumns.php
  resources/assets/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/rejection-modal.blade.php
Labels: HR, status : ready for review

#231 (#61) Ability to schedule datetime and person
  app/Http/Controllers/HR/ApplicationController.php
  app/Http/Controllers/HR/JobController.php
  app/Http/Requests/HR/ApplicationRoundRequest.php
  app/Models/HR/ApplicationRound.php
  app/User.php
  config/constants.php
  resources/assets/sass/app.scss
  resources/views/hr/application/edit.blade.php
Labels: status : reviewed

#236 (#61) Sending notification to the scheduled user
  app/Models/HR/ApplicationRound.php
  app/Notifications/HR/ApplicationRoundScheduled.php
  config/app.php
Labels: HR, status : ready for review

#230 (#221) showing applicant timeline
  app/Http/Controllers/HR/ApplicationController.php
  app/Models/HR/Applicant.php
  app/Models/HR/Application.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/timeline.blade.php
Labels: status : reviewed

#226 Tracking internship applications
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Controllers/HR/Applications/InternshipApplicationController.php
  app/Http/Controllers/HR/Applications/JobApplicationController.php
  app/Http/Requests/HR/ApplicantRequest.php
  app/Models/HR/Applicant.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  app/Models/HR/ApplicationRound.php
  app/Models/HR/Job.php
  composer.lock
  database/migrations/2018_05_17_091132_add_type_to_job.php
  database/migrations/2018_05_17_122653_add_h_r_application_meta_table.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/job/edit.blade.php
  resources/views/hr/job/index.blade.php
  resources/views/hr/menu.blade.php
  routes/web.php
Labels: status : reviewed

#234 (#140) Add books category
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Http/Requests/KnowledgeCafe/Library/BookRequest.php
  config/constants.php
  database/seeds/DatabaseSeeder.php
  resources/assets/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
  routes/web.php
Labels: status : reviewed

#251 #241 applicant job links
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Models/HR/Application.php
Labels: status : reviewed

#253 #252 job authorisation correction
  app/Http/Controllers/HR/JobController.php
Labels: HR, status : reviewed

#258 (#257) schedule next round
  app/Http/Requests/HR/ApplicationRoundRequest.php
  app/Models/HR/ApplicationRound.php
  resources/assets/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/round-review-confirm-modal.blade.php
Labels: HR, status : reviewed

#256 (#255) sorting applications based on date created (applied on)
  app/Http/Controllers/HR/Applications/ApplicationController.php
Labels: status : reviewed

#238 (#61) Sending notification to the scheduled user
  .env.example
  app/Listeners/HR/CreateFirstApplicationRound.php
  app/Models/HR/Applicant.php
  app/Models/HR/ApplicationRound.php
  app/Notifications/HR/ApplicationRoundScheduled.php
  app/Observers/HR/ApplicationRoundObserver.php
  app/Providers/DatabaseServiceProvider.php
  config/app.php
Labels: HR, status : reviewed

#260 #250 update json column to text for support across mysql versions
  database/migrations/2018_05_17_122653_add_h_r_application_meta_table.php
  database/migrations/2018_05_22_062339_update_application_meta_table.php
Labels: status : reviewed

#259 #254 inline resume
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/inline-resume.blade.php
Labels: status : ready for review

#264 (#263) recovering round feedback
  app/Http/Requests/HR/ApplicationRoundRequest.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/round-review-confirm-modal.blade.php
Labels: HR, status : reviewed

#271 (#140) multiple category
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Http/Requests/KnowledgeCafe/Library/BookRequest.php
  app/Models/KnowledgeCafe/Library/Book.php
  app/Models/KnowledgeCafe/Library/BookCategory.php
  config/constants.php
  database/migrations/2018_05_22_091018_create_books_category_table.php
  database/migrations/2018_05_22_091052_create_library_book_category_table.php
  database/migrations/2018_05_22_091814_remove_book_category_column.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/show.blade.php
  resources/views/knowledgecafe/library/books/update-category-modal.blade.php
Labels: status : reviewed

#274 (#268) job to internship
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Requests/HR/ApplicationRequest.php
  app/Mail/HR/Application/JobChanged.php
  app/Models/HR/Applicant.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  app/Models/HR/ApplicationRound.php
  config/constants.php
  database/migrations/2018_05_22_193854_update_h_r_application_meta_table.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/timeline.blade.php
  resources/views/hr/communication-mail-modal.blade.php
  resources/views/hr/job-to-internship-modal.blade.php
  resources/views/hr/round-review-sent-mail-modal.blade.php
  routes/web.php
Labels: HR, status : reviewed

#280 (#279) BCC to HR group
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Mail/HR/Applicant/RoundReviewed.php
Labels: HR, status : reviewed

#275 travis ci test for mysql v5.7
  .travis.yml
Labels: status : ready for review

#281 #272 deafult zoom added
  resources/views/hr/application/inline-resume.blade.php
Labels: HR, status : reviewed

#287 #282 Application Review table renamed to application round review
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Models/HR/ApplicationRound.php
  app/Models/HR/ApplicationRoundReview.php
  database/migrations/2018_05_24_085436_change_application_review_table_name.php
  database/seeds/MigrateApplicantJobReferenceSeeder.php
  resources/views/hr/application/edit.blade.php
Labels: HR, status : reviewed

#283 (#265) round default template
  app/Http/Controllers/HR/RoundController.php
  app/Http/Controllers/SettingController.php
  app/Http/Requests/HR/RoundRequest.php
  app/Models/HR/Round.php
  database/migrations/2018_05_23_165429_update_hr_rounds_add_round_mail_templates.php
  resources/views/hr/round-guide-modal.blade.php
  resources/views/hr/round-review-mail-modal.blade.php
  resources/views/settings/hr.blade.php
  routes/web.php
Labels: HR, status : reviewed

#298 #296 resume flash cloaked
  resources/assets/sass/app.scss
  resources/views/hr/application/inline-resume.blade.php
Labels: status : reviewed

#300 (#285) round not conducted
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Requests/HR/ApplicationRequest.php
  app/Mail/HR/Application/RoundNotConducted.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  app/Models/HR/ApplicationRound.php
  app/Models/Setting.php
  config/constants.php
  resources/assets/sass/app.scss
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/timeline.blade.php
  resources/views/hr/round-not-conducted-modal.blade.php
  resources/views/settings/hr.blade.php
  resources/views/settings/hr/applicant-auto-responder.blade.php
  resources/views/settings/hr/round-not-conducted.blade.php
Labels: status : reviewed

#299 (140) new book category
  app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Http/Requests/KnowledgeCafe/Library/BookCategoryRequest.php
  app/Models/KnowledgeCafe/Library/BookCategory.php
  app/Policies/KnowledgeCafe/Library/BookCategoryPolicy.php
  app/Providers/AuthServiceProvider.php
  database/migrations/2018_05_25_172849_update_book_categories_table.php
  database/seeds/BookCategoriesPermissionsSeeder.php
  resources/assets/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/update-category-modal.blade.php
  resources/views/knowledgecafe/library/categories/index.blade.php
  resources/views/knowledgecafe/library/menu.blade.php
  routes/web.php
Labels: status : reviewed

#307 (#291) job observer implemented
  app/Events/HR/JobCreated.php
  app/Http/Controllers/HR/JobController.php
  app/Listeners/HR/CreateJobRounds.php
  app/Models/HR/Job.php
  app/Observers/HR/JobObserver.php
  app/Providers/DatabaseServiceProvider.php
  app/Providers/EventServiceProvider.php
Labels: status : reviewed

#246 #235 small reporting section on application dashboard
  .env.example
  app/Http/Controllers/HR/Applications/ApplicationController.php
  resources/views/hr/application/index.blade.php
Labels: HR, status : reviewed

#308 (#309) home ui fix for employee roles
  resources/views/home.blade.php
Labels: status : ready for review

#288 282 checklist round review
  app/Models/HR/ApplicationRoundReviewEvaluation.php
  app/Models/HR/EvaluationParameter.php
  app/Models/HR/EvaluationParameterOption.php
  app/Models/HR/Round.php
  database/migrations/2018_05_24_093123_add_evaluation_parameter_table.php
Labels: status : reviewed

#305 On hold applications tab
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Models/HR/Applicant.php
  app/Models/HR/Application.php
  resources/views/hr/application/index.blade.php
Labels: status : reviewed

#323 (#320) Unit test cases in HR
  tests/Unit/HR/ApplicantControllerTest.php
  tests/Unit/HR/ApplicantTest.php
  tests/Unit/HR/JobControllerTest.php
  tests/Unit/HR/JobTest.php
  tests/Unit/HR/RoundTest.php
Labels: status : reviewed

#319 (#311) no show
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Requests/HR/ApplicationRequest.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  app/Models/HR/ApplicationRound.php
  app/Models/Setting.php
  config/constants.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/timeline.blade.php
  resources/views/hr/no-show-modal.blade.php
  resources/views/settings/hr.blade.php
  resources/views/settings/hr/no-show.blade.php
  resources/views/settings/hr/round-not-conducted.blade.php
Labels: status : reviewed

#324 Modify dashboard tab position
  resources/views/hr/application/index.blade.php
Labels: status : ready for review
