Repository ColoredCow/portal, pull requests merged in 2018-07, with the labels that each got.

#537 Volunteer manager
  app/Http/Controllers/HR/JobController.php
  app/Policies/HR/JobPolicy.php
  database/seeds/DatabaseSeeder.php
  database/seeds/VolunteersModuleSeeder.php
  resources/views/hr/job/edit.blade.php
  resources/views/hr/job/index.blade.php
  resources/views/hr/menu.blade.php
  routes/web.php
Labels: status : ready for review

#495 dropdown will appear when application is rejected
  resources/views/hr/application/edit.blade.php
Labels: status : ready for review

#542 Fixes number of open applications in the job listing page
  app/Http/Controllers/HR/JobController.php
  app/Http/Controllers/HR/Volunteers/VolunteerOpportunityController.php
  resources/views/hr/job/index.blade.php
Labels: status : reviewed

#535 Welcome page
  app/Http/Middleware/TenantMiddleware.php
  app/Models/KnowledgeCafe/Library/Book.php
  app/Providers/TenantServiceProvider.php
  app/Services/TenantService.php
  public/cc-logo.png
  public/images/background-min.png
  resources/assets/sass/welcome.scss
  resources/views/welcome.blade.php
  routes/web.php
  webpack.mix.js
Labels: status : reviewed

#548 185 create invoice billing stage
  app/Http/Controllers/Finance/InvoiceController.php
  database/migrations/2018_07_05_162630_change_finance_invoices_table.php
Labels: status : ready for review, status : reviewed

#505 345 ui fix home page
  resources/views/crm/index.blade.php
  resources/views/home.blade.php
  resources/views/hr/index.blade.php
  resources/views/knowledgecafe/index.blade.php
Labels: status : ready to test, status : reviewed

#557 (#545) menu fix
  app/Http/Controllers/HR/Applications/ApplicationController.php
  config/constants.php
Labels: status : reviewed

#549 Total Receivable balance to Finance Report
  app/Http/Controllers/Finance/ReportsController.php
  resources/views/finance/reports/index.blade.php
Labels: status : ready for review

#518 (#517) employee test coverage
  database/factories/EmployeeFactory.php
  routes/web.php
  tests/Feature/FeatureTest.php
  tests/Feature/HR/EmployeeTest.php
  tests/Feature/ProjectsTest.php
  tests/Unit/ExampleTest.php
  tests/Unit/HR/EmployeeTest.php
  tests/Unit/UserTest.php
  tests/utilities/functions.php
Labels: HR, status : development

#554 463 status modal doesn't disappear on clicking x button
  resources/assets/js/app.js
Labels: status : ready to test

#558 book card width increased for tablet screen (> 767px)
  resources/assets/sass/app.scss
Labels: status : ready to test

#536 378 custom emails
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Controllers/HR/Applications/JobApplicationController.php
  app/Http/Requests/HR/CustomApplicationMailRequest.php
  app/Mail/HR/Application/CustomApplicationMail.php
  config/constants.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/custom-application-mail-modal.blade.php
  routes/web.php
Labels: status : ready for build

#562 g-suite require full name
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Requests/HR/ApplicantRequest.php
Labels: status : ready for build

#550 459 paid status
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  resources/assets/js/components/ProjectStageComponent.vue
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
Labels: status : ready to test, status : reviewed

#615 613 onboard applicants
  app/Models/HR/Application.php
  app/Models/HR/ApplicationRound.php
  resources/assets/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/onboard-applicant-modal.blade.php
Labels: status : ready to test

#591 458 amount should not show zero
  resources/assets/js/components/ProjectStageBillingComponent.vue
  resources/assets/js/components/ProjectStageComponent.vue
Labels: status : ready to test

#614 607 store stages using ajax
  app/Http/Controllers/ProjectStageController.php
  resources/assets/js/components/ProjectStageComponent.vue
  resources/views/project/edit.blade.php
  routes/web.php
Labels: status : ready to test, status : reviewed

#616 (#566) test case cleanups
  tests/Feature/FeatureTest.php
  tests/Feature/HR/EmployeeTest.php
  tests/Feature/KnowledgeCafe/Library/BookTest.php
  tests/Feature/ProjectTest.php
  tests/TestCase.php
  tests/Unit/KnowledgeCafe/Library/BookTest.php
Labels: status : ready for review

#589 admin have abilty to sync all employee
  app/Http/Controllers/UserController.php
  app/Policies/UserPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Services/GSuiteUserService.php
  app/User.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: status : ready for review

#597 (#563) ui for superadmin
  app/Http/Controllers/SettingController.php
  app/Http/Controllers/Settings/HRController.php
  app/Http/Controllers/Settings/PermissionController.php
  app/Http/Controllers/Settings/SettingController.php
  app/Http/Requests/Setting/SettingRequest.php
  app/Http/Requests/Setting/UpdateRolePermissionsRequest.php
  app/Http/Requests/Setting/UpdateUserRolesRequest.php
  resources/assets/js/app.js
  resources/views/layouts/app.blade.php
  resources/views/settings/hr/index.blade.php
  resources/views/settings/index.blade.php
  resources/views/settings/permissions/roles.blade.php
  resources/views/settings/permissions/update-role-permissions-modal.blade.php
  resources/views/settings/permissions/update-user-roles-modal.blade.php
  resources/views/settings/permissions/users.blade.php
  routes/web.php
Labels: status : ready to test

#485 337 removed reason for eligibility
  app/Http/Requests/HR/ApplicantRequest.php
  app/Models/HR/Applicant.php
  database/migrations/2018_06_19_060844_hr_application_remove_reason_for_eligibility.php
  database/seeds/MoveReasonForEligibilitySeeder.php
  resources/views/hr/application/edit.blade.php
Labels: status : ready for build

#628 273 book can have multiple copies
  app/Http/Requests/KnowledgeCafe/Library/BookRequest.php
  app/Models/KnowledgeCafe/Library/Book.php
  database/migrations/2018_07_25_121709_add_column_number_of_copies.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/info.blade.php
  tests/Feature/KnowledgeCafe/Library/BookTest.php
Labels: status : ready to test
