Repository ColoredCow/portal, pull requests merged in 2018-06, with the labels that each got.

#330 Removed started_at from project listing #156
  resources/views/project/index.blade.php
Labels: status : reviewed

#327 (#311) no show scheduling
  app/Console/Commands/HR/ApplicationNoShow.php
  app/Console/Kernel.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  config/constants.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/timeline.blade.php
Labels: status : ready for review

#326 282 checklist round review show question
  app/Http/Controllers/HR/ApplicationRoundController.php
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Http/Requests/HR/ApplicationRoundRequest.php
  app/Models/HR/ApplicationRound.php
  app/Models/HR/ApplicationRoundEvaluation.php
  app/Models/HR/ApplicationRoundReview.php
  app/Models/HR/Round.php
  database/migrations/2018_05_25_172849_update_book_categories_table.php
  database/migrations/2018_05_31_095251_update_evaluation_tables.php
  database/seeds/ResumeScreeningEvaluationSeeder.php
  resources/assets/sass/app.scss
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/round-evaluation.blade.php
Labels: status : ready for review

#342 Delete books
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  database/migrations/2018_06_01_122319_update_library_books_table.php
  resources/assets/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#348 Search books
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  resources/assets/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#352 #(books api)
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  routes/api.php
Labels: status : reviewed

#351 (#285) pre interview reminders
  app/Console/Commands/HR/SendInterviewReminders.php
  app/Console/Kernel.php
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Mail/HR/Applicant/ScheduledInterviewReminder.php
  app/Mail/HR/InterviewerScheduledRoundsReminder.php
  app/Models/HR/ApplicationRound.php
  config/constants.php
  resources/views/mail/hr/interviewer-scheduled-rounds-reminder.blade.php
  resources/views/settings/hr.blade.php
  resources/views/settings/hr/applicant-interview-reminder.blade.php
Labels: status : ready for review

#360 (#285) interview reminder enable
  app/Console/Commands/HR/SendInterviewReminders.php
  database/migrations/2018_06_04_120633_update_round_table_reminder_enabled_column.php
Labels: HR, status : ready for review

#356 Mark book as read
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  database/migrations/2018_06_03_174331_create_book_readers_table.php
  resources/assets/js/app.js
  resources/views/home.blade.php
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/show.blade.php
  resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
  routes/web.php
Labels: status : reviewed

#363 (#357) No show reminder
  app/Console/Commands/HR/ApplicationNoShow.php
  app/Mail/HR/Applicant/NoShow.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationMeta.php
  app/Models/Setting.php
  app/Observers/HR/ApplicationMetaObserver.php
  app/Providers/DatabaseServiceProvider.php
  config/constants.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/timeline.blade.php
  resources/views/hr/communication-mail-modal.blade.php
  resources/views/hr/no-show-modal.blade.php
Labels: HR, status : ready for review

#388 (#386) no-show status change to in-progress
  app/Console/Commands/HR/ApplicationNoShow.php
  app/Listeners/HR/CreateFirstApplicationRound.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationRound.php
Labels: HR, status : reviewed

#391 (#390) conducted date bug
  resources/assets/sass/app.scss
  resources/views/hr/application/edit.blade.php
Labels: status : reviewed

#394 (#393) change books UI
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  app/User.php
  database/migrations/2018_06_07_104415_update_users_table_with_avatar_column.php
  database/migrations/2018_06_07_133212_create_table_book_wishlist.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/home.blade.php
  resources/views/knowledgecafe/library/books/show.blade.php
  resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
  routes/web.php
Labels: status : reviewed

#397 #335 Dependencies removed in the same namespace in finance module
  app/Models/Client.php
  app/Models/Project.php
  app/Models/ProjectStageBilling.php
Labels: Finance, status : ready for review

#396 377 question pool
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationRound.php
  app/Models/HR/ApplicationRoundEvaluation.php
  app/Models/HR/Evaluation/ApplicationEvaluation.php
  app/Models/HR/Evaluation/Parameter.php
  app/Models/HR/Evaluation/ParameterOption.php
  app/Models/HR/Evaluation/Segment.php
  app/Models/HR/Round.php
  database/migrations/2018_06_08_075242_update_round_review_table.php
  database/migrations/2018_06_08_171410_add_evaluation_segment.php
  database/seeds/ApplicationEvaluationSeeder.php
Labels: HR, status : reviewed

#399 #377 Updates to show answered evaluation in a sidebar
  app/Http/Controllers/HR/Applications/ApplicationController.php
  app/Models/HR/Application.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/hr/application/application-evaluation.blade.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/inline-resume.blade.php
Labels: HR, status : reviewed

#384 346 knowledge cafe as a dropdown in primary navigation
  app/Providers/AuthServiceProvider.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: status : reviewed

#367 Job issue 164
  app/Http/Controllers/Finance/InvoiceController.php
  app/Providers/AppServiceProvider.php
  database/migrations/2018_06_04_132230_due_date.php
  resources/views/finance/invoice/create.blade.php
Labels: status : reviewed

#423 Hot fix
  resources/assets/sass/app.scss
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: priority : critical

#429 Read button on view
  .gitignore
  public/images/default_profile.png
  resources/assets/sass/app.scss
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/show.blade.php
Labels: status : reviewed

#443 (#422) Change book size
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  resources/assets/sass/app.scss
Labels: status : reviewed

#444 (#410) "Send for approval" action in application round
  app/Http/Requests/HR/ApplicationRoundRequest.php
  app/Models/HR/Application.php
  app/Models/HR/ApplicationRound.php
  config/constants.php
  database/migrations/2018_06_13_150744_add_column_pending_approval_from_in_application.php
  resources/assets/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/send-for-approval-modal.blade.php
  resources/views/hr/round-review-confirm-modal.blade.php
Labels: HR, status : reviewed

#385 Unit test for Project (#371)
  .env.testing
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectController.php
  composer.json
  database/factories/ClientFactory.php
  database/factories/ProjectFactory.php
  database/migrations/2018_05_22_091814_remove_book_category_column.php
  resources/views/finance/menu.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  resources/views/project/index.blade.php
  routes/web.php
  tests/Feature/ExampleTest.php
  tests/Feature/FeatureTest.php
  tests/Feature/ProjectsTest.php
  tests/TestCase.php
  tests/utilities/functions.php
Labels: status : reviewed

#419 269 error report
  .env.example
  app/Exceptions/Handler.php
  app/Http/Controllers/KnowledgeCafe/KnowledgeCafeController.php
  app/Mail/ErrorReport.php
  config/mail.php
  database/migrations/2018_03_13_132221_create_users_table.php
  resources/views/mail/error-report.blade.php
Labels: status : reviewed

#469 bootstrap is now updated on the latest version 4.1.1
  package-lock.json
  package.json
Labels: status : reviewed

#481 (#480) UI fix
  resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
Labels: status : ready for review

#465 345 UI broken in home page
  resources/assets/sass/app.scss
  resources/views/home.blade.php
  resources/views/knowledgecafe/index.blade.php
  resources/views/layouts/app.blade.php
Labels: status : reviewed

#455 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: status : reviewed

#498 (#497) billing calculation fix
  resources/assets/js/components/ProjectStageComponent.vue
Labels: status : reviewed

#515 (#514) finance reports fix
  app/Http/Controllers/Finance/ReportsController.php
  resources/assets/js/app.js
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
Labels: status : ready for review
