Repository ColoredCow/portal, pull requests merged in 2018-04, with the labels that each got.

#35 32 finance views
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/HomeController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Models/Client.php
  app/Models/Finance/Invoice.php
  app/Models/Project.php
  config/constants.php
  database/migrations/2018_03_30_132837_create_projects_table.php
  database/migrations/2018_03_30_134258_create_finance_invoices_table.php
  resources/assets/sass/app.scss
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/finance/menu.blade.php
  resources/views/home.blade.php
  routes/web.php
  tests/Unit/ExampleTest.php
  tests/Unit/Finance/InvoiceControllerTest.php
Labels: status : ready for review

#36 32 client project views
  .gitignore
  app/Helpers/DateHelper.php
  app/Helpers/FileHelper.php
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Requests/ClientRequest.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Http/Requests/ProjectRequest.php
  app/Models/Finance/Invoice.php
  app/Models/Project.php
  config/constants.php
  database/migrations/2018_03_30_134258_create_finance_invoices_table.php
  package-lock.json
  package.json
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/client/index.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  resources/views/project/index.blade.php
  routes/web.php
  tests/Unit/ClientControllerTest.php
  tests/Unit/ProjectControllerTest.php
Labels: status : ready for review

#41 (#40) invoice fields
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Models/Finance/Invoice.php
  config/constants.php
  database/migrations/2018_04_03_074727_update_finance_invoices_table.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
Labels: status : ready for review

#57 (#55) invoices projects
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Models/Finance/Invoice.php
  database/migrations/2018_04_04_160344_create_project_finance_invoices_table.php
  database/migrations/2018_04_04_160509_drop_finance_invoices_project_id_column.php
  resources/assets/js/app.js
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  routes/web.php
Labels: Finance, status : ready for review

#67 HR test coverage
  tests/Unit/HR/ApplicantControllerTest.php
  tests/Unit/HR/JobControllerTest.php
Labels: HR, status : ready for review

#73 (#68) payment type
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Models/Finance/Invoice.php
  config/constants.php
  database/migrations/2018_04_06_074924_add_finance_invoices_payment_type_column.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
Labels: Finance, priority : critical, status : ready for review

#66 (#49) validation errors
  app/Http/Requests/ClientRequest.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Http/Requests/ProjectRequest.php
  resources/assets/js/app.js
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/errors.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
Labels: Finance, status : ready for review

#81 (#70) AWS SES setup
  .env.example
  composer.json
  composer.lock
  config/mail.php
  config/services.php
Labels: status : ready for review

#83 (#63) applicant communication
  .env.example
  app/Http/Controllers/HR/ApplicantRoundController.php
  app/Http/Requests/HR/ApplicantRoundMailRequest.php
  app/Models/HR/ApplicantRound.php
  database/migrations/2018_04_07_100220_add_hr_applicant_round_communication_columns.php
  resources/assets/sass/app.scss
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/errors.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/round-review-mail-modal.blade.php
  resources/views/hr/round-review-sent-mail-modal.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  routes/web.php
Labels: HR, priority : critical, status : development

#96 (#79) Country for client. (#95) red asterisk for required field labels.
  app/Http/Controllers/ClientController.php
  app/Http/Requests/ClientRequest.php
  app/Models/Client.php
  config/constants.php
  database/migrations/2018_04_09_123937_add_clients_nationality_column.php
  resources/assets/sass/app.scss
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
Labels: Finance, status : ready for review

#103 #85 Round review editable
  app/Http/Controllers/HR/ApplicantController.php
  resources/views/hr/applicant/edit.blade.php
Labels: status : ready for review

#102 (#48) session status
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Controllers/HR/ApplicantRoundController.php
  app/Http/Controllers/HR/JobController.php
  app/Http/Controllers/ProjectController.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/job/edit.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  resources/views/status.blade.php
  routes/web.php
Labels: status : ready for review

#104 (#89) college year course
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Requests/HR/ApplicantRequest.php
  app/Models/HR/Applicant.php
  database/migrations/2018_04_11_090335_update_applicant_add_college.php
  resources/views/client/index.blade.php
  resources/views/hr/applicant/edit.blade.php
Labels: status : ready for review

#84 (#52) more project details
  .gitignore
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Controllers/ProjectStageController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  app/Http/Requests/ProjectRequest.php
  app/Http/Requests/ProjectStageRequest.php
  app/Models/Finance/Invoice.php
  app/Models/Project.php
  app/Models/ProjectStage.php
  app/Models/ProjectStageBilling.php
  config/constants.php
  database/migrations/2018_04_07_122230_additional_detail_projects.php
  database/migrations/2018_04_10_083321_create_project_stages_table.php
  database/migrations/2018_04_10_084348_create_project_stage_billings_table.php
  database/migrations/2018_04_10_085404_create_project_stage_billing_invoices_table.php
  database/migrations/2018_04_12_060026_add_finance_invoices_gst_column.php
  resources/assets/js/app.js
  resources/assets/js/components/ProjectStageBillingComponent.vue
  resources/assets/js/components/ProjectStageComponent.vue
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  routes/web.php
Labels: status : ready for review

#112 cheque-status field
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Requests/Finance/InvoiceRequest.php
  config/constants.php
  database/migrations/2018_04_13_050647_add_finance_invoices_cheque_status_column.php
  resources/assets/js/app.js
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
Labels: HR, status : ready for review

#114 (#29) applicant timeline
  resources/assets/sass/app.scss
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/applicant/timeline.blade.php
Labels: HR, status : ready for review

#111 (#65) method guide
  app/Http/Controllers/HR/RoundController.php
  app/Http/Requests/HR/RoundRequest.php
  app/Models/HR/Round.php
  database/migrations/2018_04_12_122532_add_hr_rounds_guide_column.php
  resources/assets/js/app.js
  resources/assets/sass/app.scss
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/round-guide-modal.blade.php
  routes/web.php
Labels: HR, status : ready for review

#119 #46 Added favicon
  public/favicon.png
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
  tests/Feature/ExampleTest.php
Labels: status : ready for review

#122 #37 pagination applied to list
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Controllers/WeeklyDoseController.php
  app/Models/Finance/Invoice.php
  app/Models/Project.php
  config/constants.php
  resources/views/client/index.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/hr/applicant/index.blade.php
  resources/views/project/index.blade.php
  resources/views/weeklydose.blade.php
Labels: status : ready for review

#123 (#121) hr changes
  app/Events/HR/ApplicantUpdated.php
  app/Http/Controllers/HR/ApplicantController.php
  app/Http/Controllers/HR/ApplicantRoundController.php
  app/Http/Requests/HR/ApplicantRoundRequest.php
  app/Listeners/HR/CreateFirstApplicantRound.php
  app/Listeners/HR/UpdateApplicantRound.php
  app/Models/HR/Applicant.php
  app/Models/HR/ApplicantRound.php
  app/Providers/EventServiceProvider.php
  config/constants.php
  resources/assets/js/app.js
  resources/assets/js/components/HR/ApplicantRoundActionComponent.vue
  resources/assets/sass/app.scss
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/applicant/index.blade.php
  resources/views/hr/applicant/timeline.blade.php
  resources/views/hr/round-review-mail-modal.blade.php
  resources/views/hr/round-review-sent-mail-modal.blade.php
  routes/web.php
Labels: HR, priority : high, status : ready for review

#124 (#75) Ui enhancements
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/client/index.blade.php
  resources/views/finance/invoice/create.blade.php
  resources/views/finance/invoice/edit.blade.php
  resources/views/finance/invoice/index.blade.php
  resources/views/finance/menu.blade.php
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/applicant/index.blade.php
  resources/views/hr/job/edit.blade.php
  resources/views/hr/job/index.blade.php
  resources/views/hr/menu.blade.php
  resources/views/layouts/app.blade.php
  resources/views/project/create.blade.php
  resources/views/project/edit.blade.php
  resources/views/project/index.blade.php
  resources/views/status.blade.php
Labels: status : ready for review

#126 (#51) Invoice Files
  app/Helpers/FileHelper.php
  app/Http/Controllers/Finance/InvoiceController.php
  resources/views/finance/invoice/index.blade.php
Labels: Finance, status : reviewed

#134 (#91) interviewers dropdown
  app/Http/Controllers/HR/JobController.php
  app/Listeners/HR/AutoRespondApplicant.php
  app/Models/HR/Job.php
  database/migrations/2018_04_22_133003_update_hr_jobs_rounds_table_by_replacing_hr_round_interviewer_user_id.php
  resources/views/hr/job/edit.blade.php
Labels: status : reviewed

#125 (#54) Added GST No
  app/Http/Controllers/ClientController.php
  app/Http/Requests/ClientRequest.php
  app/Models/Client.php
  database/migrations/2018_04_16_084105_update_client_with_gst_number_column.php
  resources/assets/js/app.js
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
Labels: Finance, status : reviewed

#137 (#133) applicant changes
  app/Http/Controllers/HR/ApplicantController.php
  app/Models/HR/Applicant.php
  app/Models/HR/ApplicantRound.php
  resources/assets/sass/app.scss
  resources/views/hr/applicant/edit.blade.php
  resources/views/hr/applicant/index.blade.php
  resources/views/hr/applicant/timeline.blade.php
Labels: HR, status : reviewed

#136 (#135) Setup library module
  app/Http/Controllers/KnowledgeCafe/KnowledgeCafeController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Http/Requests/KnowledgeCafe/Library/BookRequest.php
  app/Services/BookServices.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  resources/assets/js/app.js
  resources/views/home.blade.php
  resources/views/knowledgecafe/index.blade.php
  resources/views/knowledgecafe/library/books/create.blade.php
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/info.blade.php
  resources/views/knowledgecafe/library/menu.blade.php
  routes/web.php
  webpack.mix.js
Labels: status : reviewed

#144 (#74) client status
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/Finance/InvoiceController.php
  app/Http/Controllers/ProjectController.php
  app/Http/Requests/ClientRequest.php
  app/Models/Client.php
  composer.lock
  database/migrations/2018_04_30_045619_add_client_status_column.php
  resources/assets/js/app.js
  resources/views/client/create.blade.php
  resources/views/client/edit.blade.php
  resources/views/client/index.blade.php
Labels: status : reviewed
