Repository ColoredCow/portal, pull requests merged in 2021-09, with the labels that each got.

#928 Added opportunity show up in website category list
  Modules/HR/Config/config.php
  Modules/HR/Observers/Recruitment/JobObserver.php
Labels: status : ready for review, module : hr

#924 Added javascript code for hiding previous dates
  Modules/HR/Http/Requests/Recruitment/JobRequest.php
  resources/js/app.js
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: status : ready for review, module : hr

#920 Creation of reports file
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  Modules/HR/Routes/web.php
  composer.json
  composer.lock
  config/app.php
  config/database.php
  docs/installation.md
  package-lock.json
  package.json
  resources/js/app.js
  resources/sass/app.scss
  resources/views/hr/recruitment/reports.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: status : ready for review

#935 Hotfix/finance conversion rate
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  app/Http/Controllers/Finance/PaymentController.php
  app/Http/Controllers/Finance/ReportsController.php
  app/Http/Requests/Finance/PaymentRequest.php
  database/Seeders/MigrateFinanceInvoiceToInvoice.php
  resources/js/components/Finance/Payment.vue
Labels: status : ready for review

#940 Soled the view button issue
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#915 Option to add, edit, update, delete remove tags
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Controllers/TagsController.php
  Modules/HR/Http/Requests/TagRequest.php
  Modules/HR/Resources/views/layouts/master.blade.php
  Modules/HR/Resources/views/tags/create-tag-modal.blade.php
  Modules/HR/Resources/views/tags/edit.blade.php
  Modules/HR/Resources/views/tags/index.blade.php
  Modules/HR/Routes/web.php
  database/migrations/2021_08_26_131040_rename_name_in_tags_table.php
  resources/views/hr/application/index.blade.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review, type : feature, module : hr

#963 Added some code formatter in pre-requisites
  docs/prerequisites.md
Labels: status : ready for review, documentation

#961 Make website database optional
  .env.example
  Modules/HR/Observers/Recruitment/JobObserver.php
  Modules/User/Services/UserService.php
  Modules/User/Traits/HasWebsiteUser.php
  app/Listeners/RemoveUserFromWebsite.php
  app/Services/WebsiteUserService.php
  config/database.php
  docs/installation.md
Labels: status : ready for review, type : enhancement 🚀

#942 Reject
  Modules/HR/Config/config.php
  Modules/HR/Entities/ApplicationRound.php
  Modules/HR/Entities/HRRejectionReason.php
  Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
  Modules/HR/Routes/web.php
  database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
  resources/js/app.js
  resources/views/hr/application/rejection-modal.blade.php
  resources/views/layouts/app.blade.php
Labels: status : ready for review

#971 tag name rename to name
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Controllers/TagsController.php
  Modules/HR/Resources/views/tags/edit.blade.php
  Modules/HR/Resources/views/tags/index.blade.php
  database/migrations/2021_09_11_154243_update_tag_table.php
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#968 Add WordPress database fields to env file
  .env.example
  config/database.php
  docs/installation.md
Labels: status : reviewed, type : enhancement 🚀

#975 Updated calling of tags view according to laravel
  Modules/HR/Http/Controllers/TagsController.php
  Modules/HR/Resources/views/tags/index.blade.php
Labels: type : bug 🐛

#988 Dropdown for Assignee and Status not working
  resources/views/layouts/app.blade.php
Labels: status : ready for review

#978 Fixed issues related to environment variables
  Modules/HR/Observers/Recruitment/JobObserver.php
  Modules/User/Services/UserService.php
  Modules/User/Traits/HasWebsiteUser.php
  app/Listeners/RemoveUserFromWebsite.php
  app/Services/WebsiteUserService.php
  config/database.php
Labels: status : reviewed

#984 Move project related migration to project Module
  Modules/Project/Database/Migrations/2021_09_09_082632_update_tables_for_effort_tracking.php
  database/migrations/2021_09_11_154243_update_tag_table.php
Labels: status : reviewed

#991 Solved the error showing in the console
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  resources/js/app.js
  resources/sass/app.scss
  resources/views/hr/recruitment/reports.blade.php
Labels: status : reviewed

#1011 Hotfix: App slots fix
  Modules/AppointmentSlots/Config/config.php
  Modules/AppointmentSlots/Services/AppointmentSlotsService.php
Labels: status : reviewed, status : ready for build

#951 Project hours
  Modules/Project/Http/Requests/ProjectRequest.php
  Modules/Project/Resources/views/subviews/create-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : reviewed

#1010 Created blade file for displaying error message
  Modules/AppointmentSlots/Http/Controllers/AppointmentSlotsController.php
  Modules/AppointmentSlots/Resources/views/select_appointments/interview_schedule_error_message.blade.php
  Modules/AppointmentSlots/Services/AppointmentSlotsService.php
  public/icons/exclamation-circle.svg
  resources/sass/app.scss
Labels: status : reviewed

#1014 Added domain names to config file same as main website
  Modules/HR/Config/config.php
Labels: status : reviewed

#994 Update prerequisites.md
  docs/installation.md
Labels: status : ready for review

#973 Feature/UI/job applications dashboard
  Modules/HR/Resources/assets/sass/app.scss
  public/icons/clipboard-check.svg
  public/icons/clipboard.svg
  public/icons/code.svg
  public/icons/exclamation-octagon-fill.svg
  public/icons/pause-circle.svg
  public/icons/people.svg
  public/icons/person-check.svg
  public/icons/x-circle.svg
  resources/js/app.js
  resources/sass/app.scss
  resources/views/hr/application/index.blade.php
Labels: status : reviewed

#980 The symbol is removed while downloading
  Modules/Invoice/Services/InvoiceService.php
Labels: status : reviewed

#987 All the TDS are rounded to 2 decimal poimts
  Modules/Invoice/Resources/views/tax-report.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1007 Changes made in installation file to make the download
  docs/installation.md
Labels: status : ready for review

#1025 Release into master
  Modules/AppointmentSlots/Config/config.php
  Modules/AppointmentSlots/Services/AppointmentSlotsService.php
Labels: status : ready for review

#1002 969 Added seeders for effort tracking
  Modules/Client/Database/factories/ClientFactory.php
  Modules/Client/Entities/Client.php
  Modules/HR/Observers/EmployeeObserver.php
  Modules/Project/Database/Seeders/ProjectDatabaseSeeder.php
  Modules/Project/Database/Seeders/ProjectTeamMemberDatabaseSeeder.php
  Modules/Project/Database/Seeders/ProjectTeamMembersEffortDatabaseSeeder.php
  Modules/Project/Database/factories/ProjectFactory.php
  Modules/Project/Database/factories/ProjectTeamMemberFactory.php
  Modules/Project/Database/factories/ProjectTeamMembersEffortFactory.php
  Modules/Project/Entities/Project.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Entities/ProjectTeamMembersEffort.php
  Modules/User/Database/Seeders/UserDatabaseSeeder.php
  Modules/User/Database/factories/UserFactory.php
  Modules/User/Entities/User.php
  database/factories/ProjectFactory.php
  phpstan.neon
Labels: status : reviewed

#1026 Changed the correct name of the config files
  Modules/Invoice/Resources/views/tax-report.blade.php
Labels: status : ready for review

#1022 Doc/965/cypress documentation
  docs/prerequisites.md
  docs/testing.md
Labels: status : ready for review

#1029 Downloading is not working fixed it
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1031 added check for currency-exchange-rate api key present in the env
  Modules/Invoice/Services/CurrencyService.php
  config/services.php
Labels: status : reviewed

#1030 Additions in Installation Guidelines
  docs/installation.md
Labels: status : ready for review

#1036 Updated the page the prerequisites and for Mac OS
  docs/prerequisites.md
Labels: status : reviewed

#1034 updated-installation-guidelines
  docs/installation.md
  package-lock.json
Labels: status : reviewed

#1005 roles and permissions
  README.md
  docs/roles-and-permissions.md
Labels: status : reviewed

#974 Feature/bootstrap/part/appointment slots
  Modules/user/Resources/views/user-settings/index.blade.php
  resources/sass/app.scss
Labels: status : reviewed

#1049 Yarn.lock removed succesfully
  yarn.lock
Labels: status : reviewed
