Repository ColoredCow/portal, pull requests merged in 2021-08, with the labels that each got.

#875 Migration failing leading to unsuccessful deployments
  database/migrations/2021_07_24_120724_rename_conversion_rate_column_in_invoice.php
Labels: status : ready for review, module : finance

#869 Updated the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status : reviewed

#871 Added the taxes in formula for calculating TDS
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: status : reviewed, module : finance

#860 Bugfix/850/resolve es lint error
  Modules/AppointmentSlots/Resources/assets/js/app.js
  Modules/EffortTracking/Resources/assets/js/app.js
  Modules/HR/Resources/assets/js/app.js
  Modules/Prospect/Resources/assets/js/components/ProspectHistory.vue
  Modules/Prospect/Resources/assets/js/components/ProspectProgressItem.vue
  Modules/Prospect/Resources/assets/js/vueComponents.js
  Modules/User/Resources/assets/js/components/RoleListing.vue
  Modules/User/Resources/assets/js/components/UpdateRolePermissionModal.vue
  Modules/User/Resources/assets/js/components/UpdateUserRoleModal.vue
  Modules/User/Resources/assets/js/components/UserListing.vue
  Modules/User/Resources/assets/js/vueComponents.js
  resources/js/bootstrap.js
  resources/js/components/Book/BooksCommentsComponent.vue
  resources/js/components/Book/ProspectProgress.vue
  resources/js/components/CommentItem.vue
  resources/js/components/Dashboard/UserDahboardInfrastructure.vue
  resources/js/components/Dashboard/UserDahboardInvocie.vue
  resources/js/components/Dashboard/UserDahboardLibrary.vue
  resources/js/components/Dashboard/UserDashboardProjects.vue
  resources/js/components/Dashboard/UserDashboardReadBooks.vue
  resources/js/components/Dashboard/UserDashboardWishlistBooks.vue
  resources/js/components/Finance/Invoice.vue
  resources/js/components/Finance/Payment.vue
  resources/js/components/HR/ApplicantRoundActionComponent.vue
  resources/js/components/InvoiceProjectComponent.vue
  resources/js/components/ProjectDetailsComponent.vue
  resources/js/components/ProjectStageBillingComponent.vue
  resources/js/components/ProjectStageComponent.vue
  resources/js/finance/invoice.js
  resources/js/finance/payment.js
Labels: status : reviewed

#876 PHP artisan error
  routes/web.php
Labels: status : reviewed

#890 Minor code formatting according to PHP-CS
  Modules/HR/Observers/Recruitment/ApplicantObserver.php
Labels: status : ready for review

#859 Update prerequisites.md
  docs/installation.md
  docs/prerequisites.md
Labels: status : reviewed

#887 #883 Team members listing
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/edit-project-resources.blade.php
Labels: status : ready for review

#895 Nothing is visible on Dashboard (due to js-errors)
  resources/js/components/CommentItem.vue
  resources/js/components/ProjectStageBillingComponent.vue
Labels: status : ready for review

#896 #892 Job opportunity description required
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: status : ready for review

#879 Feature/hr jobs/add start and end date
  Modules/HR/Entities/Job.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Http/Requests/Recruitment/JobRequest.php
  database/migrations/2021_08_11_151111_add_start_date_and_end_date_to_hr_jobs.php
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: status : ready for review, type : feature, module : hr

#889 New Job Opportunity also reflect on ColoredCow Website
  Modules/HR/Config/config.php
  Modules/HR/Observers/Recruitment/JobObserver.php
Labels: status : ready for review, type : feature, module : hr

#905 Added tabs for my projects and all projects
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Services/ProjectService.php
  Modules/User/Entities/User.php
Labels: status : ready for review, type : enhancement 🚀

#926 Solved Conversion Rate Difference Error
  Modules/Invoice/Entities/Invoice.php
  app/Http/Controllers/Finance/PaymentController.php
  app/Http/Controllers/Finance/ReportsController.php
  app/Http/Requests/Finance/PaymentRequest.php
  database/Seeders/MigrateFinanceInvoiceToInvoice.php
  resources/js/components/Finance/Payment.vue
Labels: status : ready for review
