Repository ColoredCow/portal, pull requests merged in 2021-12, with the labels that each got.

#1206 The basic setup needed for CRM
  resources/views/crm/index.blade.php
  resources/views/layouts/navbar.blade.php
  routes/web.php
Labels: status : ready for review

#1217 Feature/error page/finance invoices module
  Modules/Invoice/Resources/views/create.blade.php
  Modules/Invoice/Resources/views/edit.blade.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  resources/views/finance/invoice/index.blade.php
Labels: status : ready for review

#1215 error on some navigation links resolved
  Modules/User/webpack.mix.js
  webpack.mix.js
Labels: status : ready for review

#1176 converted total amounts to words
  Modules/Invoice/Resources/assets/js/app.js
  Modules/Invoice/Resources/views/layouts/master.blade.php
  Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
  webpack.mix.js
Labels: status : ready for review

#1218 Phase 3 solved
  Modules/Project/Database/Migrations/2021_12_10_094701_create_project_health_table.php
Labels: status : reviewed

#1213 1194-Phase-1-Project-details-page is done
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Routes/web.php
  resources/js/components/Dashboard/UserDashboardProjects.vue
Labels: status : reviewed

#1223 Guideline for setting up mailtrap in local system has been created
  docs/installation.md
Labels: status : ready for review

#1225 minor changes
  docs/installation.md
Labels: status : ready for review

#1227 Integration testing checks are failing
  .github/workflows/integration-testing.yml
Labels: status : ready to test

#1224 Corrected Permissions Table seeding
  database/Seeders/PermissionsTableSeeder.php
Labels: status : ready for review

#1198 Effortsheet cubejs
  .env.example
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Resources/views/subviews/show-project-hours.blade.php
  config/constants.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/Project/Report.vue
  resources/js/components/Project/components/BarChart.vue
  resources/js/components/Project/components/Chart.vue
  resources/js/components/Project/components/LineChart.vue
  resources/views/knowledgecafe/library/books/show.blade.php
Labels: status : reviewed, type : enhancement 🚀

#1236 Required database for the CRM
  app/Http/Controllers/CRM/CRMController.php
  app/Models/ClientCrmDetails.php
  app/Services/CRMServices.php
  database/migrations/2021_12_25_084638_create_client_crm_details_table.php
  resources/views/crm/index.blade.php
  routes/web.php
Labels: status : ready for review, module : CRM

#1226 Recruitment menu UI issue has been fixed
  resources/sass/app.scss
  resources/views/hr/application/index.blade.php
Labels: status : ready for review
