Repository ColoredCow/portal, pull requests merged in 2022-12, with the labels that each got.

#2679 apply the curser pointer in Evaluate button
  Modules/HR/Resources/views/application/render-application-row.blade.php
Labels: status : ready for review

#2689 showing work history of developer
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Routes/web.php
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/edit-project-techstack-details.blade.php
  Modules/Project/Services/ProjectService.php
  resources/views/hr/employees/employee-work-history.blade.php
  resources/views/hr/employees/show.blade.php
Labels: status : ready for review

#2705 Feature/provide designation id #2659,2660,2661,2662
  Modules/HR/Config/config.php
  Modules/Project/Config/config.php
  Modules/Project/Services/ProjectService.php
  database/Seeders/ProjectTeamMemberSeeder.php
  database/migrations/2022_12_20_122617_add_designation_id_to_project_team_members.php
Labels: status : ready to deploy

#2706 drop_column_designation
  database/migrations/2022_12_21_104041_drop_designation_column_from_project_team_members.php
Labels: status : ready for review

#2699 Team_member_getting_removed_when_halted
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready to test

#2635 ADD VALIDATION IN RECURRING EXPENSE
  Modules/Expense/Http/Controllers/RecurringExpenseController.php
  Modules/Expense/Http/Requests/RecurringExpenseRequest.php
Labels: status : ready to test

#2618 UI issue in Home screen
  resources/js/components/Dashboard/UserDashboardLibrary.vue
Labels: status : ready to test

#2673 Apply default filter invoice page
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready to test

#2735 Add 2 columns in a invoices table
  database/migrations/2022_12_28_163218_add_term_start_date_and_term_end_date_to_invoices_table.php
Labels: status : ready for review

#2740 When the user is an administrator, invoices can be deleted
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review
