Repository ColoredCow/portal, pull requests merged in 2022-08, with the labels that each got.

#2074 Cypress automated test cases
  cypress.json.example
  cypress/integration/login/login.spec.js
  cypress/support/commands.js
  database/Seeders/UsersTableSeeder.php
  package-lock.json
  resources/views/layouts/navbar.blade.php
Labels: status : reviewed

#2090 Added functionality to create custom invoice
  Modules/Client/Entities/Client.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/views/create-custom-invoice.blade.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/modals/custom-invoice-email-preview.blade.php
  Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
  Modules/Invoice/Resources/views/render/invoice-template.blade.php
  Modules/Invoice/Resources/views/subviews/create/custom-invoice.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Entities/Project.php
Labels: status : ready for review

#2056 added form validations
  Modules/HR/Http/Controllers/HrChannelController.php
  resources/js/app.js
  resources/views/hr/application/create.blade.php
Labels: status : reviewed, UI/UX 🎨

#2096 Button Allignment Fixed
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#2098 show the toast messages
  resources/js/app.js
Labels: status : reviewed

#2064 FTE details of the Key account manager should not be displayed to the…
  Modules/Client/Resources/views/subviews/listing-client-row.blade.php
Labels: status : ready for review

#2022 Backend validation for evaluation segments
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Http/Requests/ManageEvaluationRequest.php
  Modules/HR/Resources/views/evaluation/index.blade.php
  Modules/HR/Resources/views/evaluation/segment/create.blade.php
  resources/js/app.js
Labels: status : ready for review

#2102 Invoice format fixes
  Modules/Invoice/Config/config.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#2092 1966/add start date end date for fixed billing projects
  Modules/Project/Http/Requests/ProjectRequest.php
  Modules/Project/Resources/views/create.blade.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Resources/views/subviews/create-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : reviewed

#2106 Hotfix for employee permissions
  Modules/HR/Policies/EmployeePolicy.php
  Modules/Project/Database/Seeders/ProjectPermissionsTableSeeder.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Policies/ProjectPolicy.php
  Modules/Project/Providers/ProjectAuthServiceProvider.php
  Modules/Project/Providers/ProjectServiceProvider.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2107 Master release sync after hotfix
  Modules/HR/Policies/EmployeePolicy.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Database/Seeders/ProjectPermissionsTableSeeder.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Policies/ProjectPolicy.php
  Modules/Project/Providers/ProjectAuthServiceProvider.php
  Modules/Project/Providers/ProjectServiceProvider.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2108 [HOTFIX] For Indian client also only the amount should be shown in payment received mail
  Modules/Invoice/Config/config.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#2109 Google Chat integration
  Modules/Project/Console/GoogleChat/RemindProjectMembersToUpdateEffortOnGoogleChat.php
  Modules/Project/Console/GoogleChat/SendDailyEffortSummaryForProjectsOnGoogleChat.php
  Modules/Project/Database/Migrations/2022_08_03_003451_add_google_chat_webhook_url_in_projects.php
  Modules/Project/Http/Requests/ProjectRequest.php
  Modules/Project/Notifications/GoogleChat/RemindToUpdateEffort.php
  Modules/Project/Notifications/GoogleChat/SendProjectSummary.php
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/create-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-financial-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-repository.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
  Modules/Project/Services/ProjectService.php
  app/Console/Kernel.php
  composer.json
  composer.lock
  config/google-chat.php
Labels: status : reviewed

#2104 Filter reset issue resolved in Monthly GST report
  Modules/Invoice/Resources/views/monthly-gst-report.blade.php
Labels: status : reviewed

#2105 Changed date format
  Modules/EffortTracking/Resources/views/show.blade.php
Labels: status : reviewed

#2126 Syncing Master and Release
  Modules/HR/Console/Recruitment/ApplicationNoShow.php
  Modules/Invoice/Config/config.php
  Modules/Invoice/Services/InvoiceService.php
  app/Console/Kernel.php
Labels: status : ready for review

#2130 2013 filter date
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#2131 Finance-Toast message added
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
Labels: status : ready for review

#2137 No show attribute modified
  Modules/HR/Entities/ApplicationRound.php
Labels: status : ready for review

#2145 [Hotfix] Time change for efforts update notification
  app/Console/Kernel.php
Labels: status : ready for review

#2146 Hotfix - failing build
  .github/workflows/production-deployment.yml
  .github/workflows/staging-deployment.yml
Labels: status : ready for review

#2120 University contact detail badge added
  Modules/HR/Resources/views/application/render-application-row.blade.php
Labels: status : ready for review

#1876 Disable the Save and Remove button available in the Project team memb…
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2139 Fixed the graph alignment
  Modules/EffortTracking/Resources/views/show.blade.php
Labels: status : ready for review

#2154 indentation fix
  Modules/HR/Resources/views/application/render-application-row.blade.php
Labels: status : ready for review

#2119 timeline and last refreshed add in project
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#2099 feature/1922/hours_column_contain_expected_no._of_days
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/EffortTracking/Services/EffortTrackingService.php
Labels: status : ready for review, status : reviewed

#2152 follow ups reminder count
  .env.example
  Modules/HR/Config/config.php
  Modules/HR/Console/Recruitment/MarkApplicationForFollowUp.php
  Modules/HR/Console/Recruitment/SendFollowUpThresholdMail.php
  Modules/HR/Emails/SendThreshholdFollowUp.php
  Modules/HR/Providers/HRServiceProvider.php
  Modules/HR/Resources/views/application/followups.blade.php
  app/Console/Kernel.php
Labels: status : reviewed

#2140 The filter for selecting start date and End date for displaying FTE should be dynamic
  Modules/EffortTracking/Http/Controllers/EffortTrackingController.php
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/EffortTracking/Services/EffortTrackingService.php
  Modules/Project/Entities/Project.php
Labels: ready for review

#2157 Creating the rate column in the project teammember table
  database/migrations/2022_08_08_184841_add__rate_column_to_project_team_members.php
Labels: status : reviewed, ready for review

#2162 Added a column named location in library books table
  database/migrations/2022_08_10_121410_add_location_column_in_library_book_table.php
Labels: status : ready for review

#2158 Audit tables created for Invoice and Project
  Modules/Invoice/Database/Migrations/2022_08_09_112351_create_invoice_audit_table.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Project/Database/Migrations/2022_08_08_222049_create_project_audit_table.php
  Modules/Project/Entities/Project.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/app.php
  config/audit.php
  database/migrations/2022_08_10_123740_create_audits_table.php
Labels: status : ready for review, status : reviewed

#2165 created a column
  database/migrations/2022_08_10_075543_add_resources_has_variable_rates_to_project_billing_detail_table.php
Labels: status : ready for review

#2100 Count of resources needed in job opportunities
  Modules/HR/Entities/Job.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
  Modules/HR/Observers/Recruitment/JobObserver.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  database/migrations/2022_08_01_113341_resources_required_column_for_hr_jobs.php
  package-lock.json
  resources/views/hr/job/index.blade.php
Labels: status : reviewed

#2123 Job role engagement
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  Modules/HR/Routes/web.php
  resources/js/app.js
  resources/views/hr/recruitment/job-Wise-Applications-Graph.blade.php
  resources/views/hr/recruitment/reportcard.blade.php
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#1934 Added a bulk applications upload feature
  Modules/HR/Config/config.php
  Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
  Modules/HR/Entities/Applicant.php
  Modules/HR/Entities/Application.php
  Modules/HR/Entities/Evaluation/ApplicationEvaluation.php
  Modules/HR/Events/Recruitment/ApplicationCreated.php
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Listeners/Recruitment/ApplicantEmailVerification.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Resources/views/evaluation/evaluation-form/knowledge.blade.php
  Modules/HR/Services/ApplicationService.php
  app/Imports/ApplicationImport.php
  public/sample-files/resume-excel.xlsx
  public/sample-files/resume_excel.xlsx
  resources/js/app.js
  resources/views/hr/application/application-evaluation.blade.php
  resources/views/hr/application/create.blade.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/evaluation-form.blade.php
  resources/views/hr/application/excel-import.blade.php
Labels: status : reviewed

#2153 user profile in employee page
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Routes/web.php
  resources/views/hr/employees/basic-details.blade.php
  resources/views/hr/employees/sub-views/menu.blade.php
Labels: status : reviewed

#2206 filtered data visible on chart
  resources/views/hr/recruitment/job-Wise-Applications-Graph.blade.php
Labels: status : reviewed

#2205 Fixing the error in project team member
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2215 Modal removed from application edit form
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/put-on-hold-modal.blade.php
Labels: status : reviewed

#2217 Reside modal inside form
  resources/views/hr/application/edit.blade.php
Labels: status : ready for review

#2208 Ability to recurring expenses in the portal
  Modules/Expense/Database/Migrations/2022_08_07_190745_create_recurring_expenses_table.php
  Modules/Expense/Entities/RecurringExpense.php
  Modules/Expense/Http/Controllers/ExpenseController.php
  Modules/Expense/Http/Controllers/RecurringExpenseController.php
  Modules/Expense/Resources/views/index.blade.php
  Modules/Expense/Resources/views/layouts/master.blade.php
  Modules/Expense/Resources/views/recurring/create.blade.php
  Modules/Expense/Resources/views/recurring/edit.blade.php
  Modules/Expense/Resources/views/recurring/index.blade.php
  Modules/Expense/Routes/web.php
  Modules/Expense/Services/RecurringExpenseService.php
  package-lock.json
  resources/views/finance/menu.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/test.blade.php
  webpack.mix.js
Labels: status : ready for review

#2203 Team interaction round mail
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Requests/TeamInteractionRequest.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  resources/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/round-review-confirm-modal.blade.php
  resources/views/settings/hr/index.blade.php
  resources/views/settings/hr/team-interaction.blade.php
Labels: status : ready for review

#2226 fixed the error
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2227 Fixed the issues with the naming convenstion of the permision
  Modules/Invoice/Http/Controllers/InvoiceController.php
Labels: status : ready for review

#2210 2198 update date filters
  resources/js/app.js
  resources/views/hr/recruitment/job-Wise-Applications-Graph.blade.php
Labels: status: Approved

#2222 changes in edit evaluation segment
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Http/Requests/EditEvaluationRequest.php
  Modules/HR/Resources/views/evaluation/index.blade.php
  Modules/HR/Resources/views/evaluation/segment/edit.blade.php
  resources/js/app.js
Labels: status : ready for review

#2212 report tab not showing
  Modules/Prospect/Resources/views/index.blade.php
Labels: status: Approved

#2211 Bugfix/borrowers can't be more
  resources/js/app.js
Labels: status: Approved

#2180 Features/aligning the contract file
  Modules/Project/Resources/views/show.blade.php
Labels: status: Approved

#2241 fixed
  Modules/HR/Resources/views/evaluation/index.blade.php
Labels: status : ready for review

#2194 2135 university reporting via automation
  Modules/HR/Http/Controllers/Universities/ReportController.php
  Modules/HR/Resources/views/universities/edit.blade.php
  Modules/HR/Resources/views/universities/menu.blade.php
  Modules/HR/Resources/views/universities/reports.blade.php
  Modules/HR/Routes/web.php
  resources/js/app.js
Labels: status : ready for review

#2230 Delete button on the Manage Evaluation
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Resources/views/evaluation/index.blade.php
  Modules/HR/Resources/views/evaluation/segment/delete.blade.php
  Modules/HR/Routes/web.php
Labels: status : reviewed

#2231 added search by category functionality
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
  routes/web.php
Labels: status : ready for review

#2242 made table user friendly
  Modules/Report/Resources/views/finance/profit-and-loss.blade.php
Labels: status : ready for review

#2221 show team members Total Expected efforts in project.
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2248 Added the fix for the segment ID not defined in the segment page
  Modules/HR/Resources/views/evaluation/index.blade.php
Labels: status : ready for review

#2188 HR reporting - rejected applications
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  Modules/HR/Routes/web.php
  resources/js/app.js
  resources/views/hr/recruitment/rejected-applications.blade.php
  resources/views/hr/recruitment/reportcard.blade.php
Labels: status : ready for review

#2258 aligned text
  resources/views/hr/recruitment/reports.blade.php
Labels: status: Approved

#2251 Feature/2249/delete functionality for sales & marketing reports
  Modules/Prospect/Resources/views/index.blade.php
  Modules/Report/Http/Controllers/ReportController.php
  Modules/Report/Resources/views/index.blade.php
  Modules/Report/Routes/web.php
Labels: status: Approved

#2247 replaced delete button
  Modules/Prospect/Resources/views/index.blade.php
Labels: status : reviewed

#2115 show total estimated hours for fixed billing projects
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Resources/views/subviews/create-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
Labels: status: Approved

#2181 Fix/1990/confirmation on taking over evaluation
  Modules/HR/Emails/Recruitment/Application/ApplicationHandover.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  resources/views/mail/hr/application-handover-request-email.blade.php
Labels: status: Approved

#2274 Revert "Fix/1990/confirmation on taking over evaluation"
  Modules/HR/Emails/Recruitment/Application/ApplicationHandover.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  resources/views/mail/hr/application-handover-request-email.blade.php
Labels: status : ready for review

#2277 Renaming done
  Modules/Project/Resources/views/index.blade.php
Labels: status : reviewed

#2276 changes added
  Modules/Client/Resources/views/index.blade.php
Labels: status : ready for review

#2271 send email check on bulk import
  Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
  Modules/HR/Listeners/Recruitment/ApplicantEmailVerification.php
  resources/views/hr/application/excel-import.blade.php
Labels: status : ready for review

#2283 Rename all the cards
  resources/views/settings/index.blade.php
Labels: status : ready for review

#2280 make the description field mandatory
  Modules/Expense/Resources/views/recurring/edit.blade.php
Labels: status : ready for review

#2279 Add client button renamed
  Modules/Client/Resources/views/index.blade.php
Labels: status : reviewed

#2292 team interaction round updated
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Requests/TeamInteractionRequest.php
  resources/js/app.js
  resources/views/hr/round-review-confirm-modal.blade.php
Labels: status : ready for review

#2294 Added Plus icon and changed the background color
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : reviewed

#2298 center aligned sales automation text
  Modules/SalesAutomation/Resources/views/index.blade.php
Labels: status : reviewed

#2303 change the color of the new opportunity button
  resources/views/hr/job/index.blade.php
Labels: status : reviewed

#2304 aligned search button with search input field
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : ready for review

#2166 Automated email to key account manager
  Modules/Project/Console/EndedProject.php
  Modules/Project/Emails/EndedProjectMail.php
  Modules/Project/Resources/views/mail/ended-project.blade.php
  Modules/Project/Services/ProjectService.php
  app/Console/Kernel.php
Labels: status: Approved

#2270 2238/features view the wish listed books
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/views/knowledgecafe/library/menu.blade.php
Labels: status : ready for review

#2311 add applications-round wise filer
  Modules/HR/Entities/Application.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#2307 plus icon added and background color changed to green
  Modules/Project/Resources/views/index.blade.php
Labels: status : reviewed

#2313 Feature/2288/added plus icon and changed the background color
  Modules/Client/Resources/views/index.blade.php
Labels: status : reviewed

#2228 Added a modal for storing reason for deletion
  Modules/Invoice/Entities/Invoice.php
Labels: status : ready for review

#2317 made add to wishlist button
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  app/Models/KnowledgeCafe/Library/Book.php
  resources/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/show.blade.php
  routes/web.php
Labels: status : ready for review
