Repository ColoredCow/portal, pull requests merged in 2022-09, with the labels that each got.

#2192 Multiple Options for on hold email
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Emails/Recruitment/Applicant/OnHold.php
  Modules/HR/Entities/ApplicationRound.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  package-lock.json
  resources/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/put-on-hold-modal.blade.php
  resources/views/settings/hr/on-hold.blade.php
Labels: status : ready for review

#2319 made the library page responsive
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : ready for review

#2297 Changing the button background color
  resources/views/knowledgecafe/library/books/show.blade.php
Labels: status : reviewed

#2344 Capitalize the first letter of placeholder text
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#2320 Feature/2097 manage evaluations round wise segments
  Modules/HR/Entities/Round.php
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Resources/views/evaluation/index.blade.php
  Modules/HR/Resources/views/evaluation/segment/edit.blade.php
  resources/sass/_variables.scss
Labels: status : ready for review

#2349 2308/fix the alignment of the View and Delete
  Modules/Report/Resources/views/index.blade.php
Labels: status : reviewed

#2348 Feature/2288/added plus icon and changed the background color
  Modules/Client/Resources/views/index.blade.php
Labels: status : reviewed

#2350 changed segment button and color
  Modules/HR/Resources/views/evaluation/index.blade.php
  Modules/HR/Resources/views/evaluation/segment-parameters.blade.php
Labels: status : ready for review

#2333 Send for approval bug Fixed
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Emails/Recruitment/SendForApproval.php
  resources/views/settings/hr/index.blade.php
  resources/views/settings/hr/send-for-approval.blade.php
Labels: status : ready for review

#2360 change button name Create channel to add book
  resources/views/hr/application/create.blade.php
Labels: status : ready for review

#2373 Features/team interaction round application should not be marked up for followup
  Modules/HR/Console/Recruitment/MarkApplicationForFollowUp.php
Labels: status : ready for review

#2376 change the alignment of the pending invoice count
  resources/js/components/Dashboard/UserDashboardInvoice.vue
Labels: status : reviewed

#2366 Modal for uploading employee docs
  Modules/User/Resources/assets/js/app.js
  Modules/User/Resources/views/profile/show-documents.blade.php
Labels: status : reviewed

#2390 Feature/2379/finance reports
  Modules/Report/Http/Controllers/FinanceReportController.php
  Modules/Report/Resources/assets/js/app.js
  Modules/Report/Resources/views/finance/dashboard.blade.php
  Modules/Report/Resources/views/finance/profit-and-loss.blade.php
  Modules/Report/Resources/views/layouts/finance.blade.php
  Modules/Report/Routes/web.php
  Modules/Report/Services/Finance/ReportDataService.php
  package-lock.json
  resources/views/layouts/navbar.blade.php
  resources/views/settings/index.blade.php
Labels: status : ready for review

#2383 Add-loading-spinner
  resources/js/app.js
  resources/sass/_variables.scss
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#2396 2384 Add intern role in the portal
  database/Seeders/RolesTableSeeder.php
Labels: status : ready for review

#2401 Fix tab content hidden
  resources/js/app.js
  resources/views/hr/application/put-on-hold-modal.blade.php
Labels: status : ready for review

#2395 made new module Revenue
  Modules/Revenue/Config/.gitkeep
  Modules/Revenue/Config/config.php
  Modules/Revenue/Console/.gitkeep
  Modules/Revenue/Database/Migrations/.gitkeep
  Modules/Revenue/Database/Seeders/.gitkeep
  Modules/Revenue/Database/Seeders/RevenueDatabaseSeeder.php
  Modules/Revenue/Database/factories/.gitkeep
  Modules/Revenue/Entities/.gitkeep
  Modules/Revenue/Http/Controllers/.gitkeep
  Modules/Revenue/Http/Controllers/RevenueController.php
  Modules/Revenue/Http/Middleware/.gitkeep
  Modules/Revenue/Http/Requests/.gitkeep
  Modules/Revenue/Providers/.gitkeep
  Modules/Revenue/Providers/RevenueServiceProvider.php
  Modules/Revenue/Providers/RouteServiceProvider.php
  Modules/Revenue/Resources/assets/.gitkeep
  Modules/Revenue/Resources/assets/js/app.js
  Modules/Revenue/Resources/assets/sass/app.scss
  Modules/Revenue/Resources/lang/.gitkeep
  Modules/Revenue/Resources/views/.gitkeep
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/layouts/master.blade.php
  Modules/Revenue/Routes/.gitkeep
  Modules/Revenue/Routes/api.php
  Modules/Revenue/Routes/web.php
  Modules/Revenue/Tests/Feature/.gitkeep
  Modules/Revenue/Tests/Unit/.gitkeep
  Modules/Revenue/composer.json
  Modules/Revenue/module.json
  Modules/Revenue/package.json
  Modules/Revenue/webpack.mix.js
  modules_statuses.json
Labels: status : ready for review

#2367 On filtering months in FTE page table is available
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/Project/Entities/ProjectTeamMember.php
Labels: status : ready for review

#2316 changed background color of <add new project> button and added plus icon before it
  Modules/Project/Resources/views/index.blade.php
Labels: status : reviewed

#2398 Fixed the navbar
  resources/sass/_variables.scss
  resources/views/layouts/app.blade.php
Labels: status : reviewed

#2403 Condition for Users Table seeder should not run on production
  database/Seeders/DatabaseSeeder.php
Labels: status : ready for review

#2330 triggering mail to keyAccountManager
  Modules/Project/Console/FixedBudgetProject.php
  Modules/Project/Emails/FixedBudgetProjectMail.php
  Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
  Modules/Project/Services/ProjectService.php
  app/Console/Kernel.php
Labels: status: Approved

#2189 functionality for zero effort projects
  Modules/Project/Console/ZeroEffortInProject.php
  Modules/Project/Emails/ZeroEffortInProjectMail.php
  Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#2408 change id's names in uplaod modal and app.js file
  Modules/User/Resources/views/profile/show-documents.blade.php
Labels: status : ready for review

#2412 Count of Total Employees
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#2334 add FTE alert and show columns
  Modules/HR/Config/config.php
  Modules/HR/Database/Migrations/2022_09_01_230847_create_job_requisition_table.php
  Modules/HR/Database/Migrations/2022_09_06_232653_add_status_to_job_requisition.php
  Modules/HR/Emails/SendHiringMail.php
  Modules/HR/Entities/Job.php
  Modules/HR/Entities/JobRequisition.php
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
  Modules/HR/Http/Controllers/RequisitionController.php
  Modules/HR/Routes/web.php
  Modules/HR/Services/RequisitionService.php
  Modules/Project/Entities/ProjectTeamMember.php
  resources/js/app.js
  resources/views/emails/send-hiring.blade.php
  resources/views/hr/employees/fte-handler.blade.php
  resources/views/hr/employees/index.blade.php
  resources/views/hr/job/index.blade.php
  resources/views/hr/requisition/complete.blade.php
  resources/views/hr/requisition/index.blade.php
  resources/views/hr/requisition/menu.blade.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2420 fix round wise filter functionality
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#2427 error in validation
  Modules/Project/Resources/views/edit.blade.php
Labels: status : ready for review, module : CRM

#2432 error in validation with latest changes
  Modules/Project/Resources/views/edit.blade.php
Labels: status : ready for review, module : CRM

#2422 fix the Tab Bug
  Modules/HR/Resources/views/application/render-application-row.blade.php
Labels: status : ready for review

#2424 Need to change no contract button using bootstrap badge class
  Modules/Project/Resources/views/index.blade.php
Labels: status : reviewed

#2410 Feature/2301/revenue module scaffolding
  Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
  Modules/Revenue/Entities/RevenueProceed.php
  Modules/Revenue/Http/Controllers/RevenueController.php
  Modules/Revenue/Http/Controllers/RevenueProceedController.php
  Modules/Revenue/Http/Requests/RevenueProceedRequest.php
  Modules/Revenue/Resources/assets/js/app.js
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/layouts/master.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
  Modules/Revenue/Routes/web.php
  Modules/Revenue/Services/RevenueProceedService.php
  resources/views/layouts/navbar.blade.php
  webpack.mix.js
Labels: status : ready for review

#2445 Added the fix for the FTE check
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/Project/Entities/ProjectTeamMember.php
Labels: status : ready for review

#2437 basic details in employees section
  Modules/HR/Http/Controllers/EmployeeController.php
  resources/views/hr/employees/basic-details.blade.php
Labels: status : ready for review, module : hr

#2415 Add option to filter the books by category
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : ready for review

#2393 trigger an email to team members if the expected hours is zero
  Modules/Project/Console/ZeroExpectedHourInProject.php
  Modules/Project/Emails/ZeroExpectedHourInProjectMail.php
  Modules/Project/Resources/views/mail/zero-expected-hours-in-project.blade.php
  Modules/Project/Services/ProjectService.php
  app/Console/Kernel.php
Labels: status : reviewed

#2462 feature/2442/enhancement in revenue proceeds
  Modules/Revenue/Database/Migrations/2022_09_15_150153_add_year_and_month_column.php
  Modules/Revenue/Resources/assets/js/app.js
  Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2444 toast message fixes
  Modules/Project/Resources/views/edit.blade.php
Labels: status : ready for review

#2441 <Added + icon to the Add New University button>
  Modules/HR/Resources/views/universities/index.blade.php
Labels: status : ready for review

#2453 Replaced the Library button to Books
  resources/js/components/Dashboard/UserDashboardLibrary.vue
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2457 only active projects are shown
  resources/views/hr/employees/show.blade.php
Labels: status : ready for review

#2465 made year and month dynamic
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2413 disabled the client database link
  Modules/SalesAutomation/Resources/views/layouts/master.blade.php
Labels: status : ready for review

#2471 Rearranged listing and added pagination
  Modules/Revenue/Entities/RevenueProceed.php
  Modules/Revenue/Http/Controllers/RevenueProceedController.php
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/list-filters.blade.php
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2331 disabling new member functionality
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#2325 Change the text color
  resources/views/knowledgecafe/library/categories/index.blade.php
Labels: status : reviewed

#2473 Added capmpaign in HR dropdown
  resources/views/hr/recruitment/campaigns.blade.php
Labels: status : ready for review

#2477 Added AMC tab
  Modules/Project/Entities/Project.php
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Resources/views/menu_header.blade.php
  Modules/Project/Services/ProjectService.php
  Modules/User/Entities/User.php
  app/Traits/Filters.php
Labels: status : reviewed

#2484 Modified the filter as financial year filter
  Modules/Revenue/Entities/RevenueProceed.php
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/list-filters.blade.php
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2474 Started capturing the average usd rates for a month.
  Modules/Invoice/Entities/CurrencyAvgRate.php
  database/migrations/2022_09_08_100613_create_currency_avg_rate.php
Labels: status : ready for review

#2488 Increase the max value
  Modules/User/Resources/views/user-settings/index.blade.php
Labels: status : ready for review

#2493 changed button title to wish listed
  resources/views/knowledgecafe/library/menu.blade.php
Labels: status : ready for review

#2498 updated message for recommended books
  resources/js/components/Dashboard/UserDashboardLibrary.vue
Labels: status : ready for review

#2502 Showed revenue procceeds in P&L reports
  Modules/Expense/Entities/Expense.php
  Modules/Report/Resources/views/finance/profit-and-loss.blade.php
  Modules/Report/Services/Finance/RevenueReportService.php
  Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
  Modules/Revenue/Database/Migrations/2022_09_20_160605_fix_typo_in_revenue_proceed_table.php
  Modules/Revenue/Entities/RevenueProceed.php
  Modules/Revenue/Http/Requests/RevenueProceedRequest.php
  Modules/Revenue/Resources/assets/js/app.js
  Modules/Revenue/Resources/views/index.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/create.blade.php
  Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2483 2443 sort universities by most application received
  Modules/HR/Resources/views/universities/index.blade.php
  Modules/HR/Services/UniversityService.php
Labels: status : ready for review

#2518 Email template fixes
  Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
  resources/views/settings/hr/index.blade.php
Labels: status : ready for review

#2353 Added Borrowed Books Tab
  Modules/User/Entities/User.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/views/knowledgecafe/library/menu.blade.php
Labels: status : reviewed

#2414 Feature/2155/interview duration
  Modules/HR/Entities/ApplicationRound.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
  Modules/HR/Routes/web.php
  Modules/HR/Services/ApplicationService.php
  database/migrations/2022_08_29_114532_create_actual_end_time_column.php
  resources/js/app.js
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/meeting-duration.blade.php
Labels: status : ready for review, module : hr

#2523 Fixed Add University button in the university listing page
  Modules/HR/Resources/views/universities/edit.blade.php
  Modules/HR/Resources/views/universities/menu.blade.php
Labels: status: Approved

#2515 Feature/2049 flagging applications
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Routes/web.php
  database/migrations/2022_09_18_161558_add_is_desired_resume.php
  resources/js/app.js
  resources/views/hr/application/desired-resume.blade.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/inline-resume.blade.php
  resources/views/hr/application/resume-table.blade.php
Labels: status : ready for review

#2524 make new module project contract
  Modules/ProjectContract/Database/Migrations/2022_09_16_110509_create_project_contract_table.php
  Modules/ProjectContract/Entities/ProjectContractMeta.php
  Modules/ProjectContract/Http/Controllers/ProjectContractController.php
  Modules/ProjectContract/Http/Requests/ProjectContractRequest.php
  Modules/ProjectContract/Resources/views/add-new-client.blade.php
  Modules/ProjectContract/Resources/views/edit-project-contract.blade.php
  Modules/ProjectContract/Resources/views/index.blade.php
  Modules/ProjectContract/Routes/web.php
  Modules/ProjectContract/Services/ProjectContractService.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2545 fix employee page fte
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review
