Repository ColoredCow/portal, pull requests merged in 2022-10, with the labels that each got.

#2527 CurrencyAvgRate table data to calculate p&l amount
  Modules/Invoice/Entities/CurrencyAvgRate.php
  Modules/Report/Services/Finance/RevenueReportService.php
Labels: status : ready for review

#2562 Show the count of wishlisted and borrowed books
  resources/views/knowledgecafe/library/menu.blade.php
Labels: status : reviewed

#2561 Now solved the problem When we select the borrowed books so only the borrowed books are displaying
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/views/knowledgecafe/index.blade.php
Labels: status : reviewed

#2392 Bug Fixed for approve round and able to send mail with pdf attached
  Modules/HR/Config/config.php
  Modules/HR/Database/Migrations/2022_09_12_140344_create_hr_applicant_meta_table.php
  Modules/HR/Database/Migrations/2022_09_26_134702_alter_column_for_application_meta_value.php
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Emails/Recruitment/SendOfferLetter.php
  Modules/HR/Entities/ApplicantMeta.php
  Modules/HR/Entities/ApplicationRound.php
  Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  Modules/HR/Http/Requests/ApplicantMetaRequest.php
  Modules/HR/Resources/views/application/render-application-row.blade.php
  Modules/HR/Routes/web.php
  Modules/HR/Services/ApplicantService.php
  app/Helpers/FileHelper.php
  config/constants.php
  resources/js/app.js
  resources/views/hr/application/approve-applicant-modal.blade.php
  resources/views/hr/application/approved-applicants-details.blade.php
  resources/views/hr/application/details-submitted.blade.php
  resources/views/hr/application/draft-joining-letter.blade.php
  resources/views/hr/application/edit.blade.php
  resources/views/hr/application/offer-letter.blade.php
  resources/views/hr/application/verify-details.blade.php
Labels: status : ready for review

#2491 add designation functionality
  Modules/HR/Config/config.php
  Modules/HR/Database/Migrations/2022_09_19_160414_create_hr_job_designation_table.php
  Modules/HR/Database/Seeders/HRDatabaseSeeder.php
  Modules/HR/Database/Seeders/HrDesignationTableSeeder.php
  Modules/HR/Entities/Employee.php
  Modules/HR/Entities/HrJobDesignation.php
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Http/Controllers/HrJobDesignationController.php
  Modules/HR/Http/Requests/ProfileEditRequest.php
  Modules/HR/Http/Requests/Recruitment/JobDesignationRequest.php
  Modules/HR/Routes/web.php
  Modules/HR/Services/HrJobDesignationService.php
  Modules/User/Http/Controllers/ProfileController.php
  Modules/User/Resources/views/profile/show-basic-details.blade.php
  Modules/User/Services/ProfileService.php
  database/migrations/2022_09_27_172448_add_designation_id_to_employees_table.php
  database/migrations/2022_09_28_164801_drop_employees_designation_column.php
  resources/js/app.js
  resources/views/hr/designations/edit.blade.php
  resources/views/hr/designations/index.blade.php
  resources/views/hr/employees/index.blade.php
  resources/views/hr/employees/show.blade.php
  resources/views/hr/job/create.blade.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2569 Feature 2566 edit delete button
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Http/Controllers/Universities/UniversityController.php
  Modules/HR/Resources/views/universities/index.blade.php
  Modules/HR/Routes/web.php
  resources/views/hr/application/edit-reason.blade.php
  resources/views/hr/application/resume-table.blade.php
Labels: status : reviewed

#2572 Changed the color and added an icon '+'
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#2435 team members are updated according to their user name
  Modules/EffortTracking/Services/EffortTrackingService.php
Labels: status: Approved

#2531 added plus icon in add university button
  Modules/HR/Resources/views/universities/index.blade.php
Labels: status : reviewed

#2351 User's review is visible while editing
  resources/js/components/CommentItem.vue
Labels: status : reviewed

#2584 HotFix: Interest on FD is not showing up on the P&L report
  Modules/Report/Config/config.php
Labels: status : ready for review

#2585 Hotfix/typo in P&L report config
  Modules/Report/Config/config.php
Labels: status : ready for review

#2577 change text input field
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#2592 Feature/report dashboard
  Modules/Report/Http/Controllers/FinanceReportController.php
  Modules/Report/Http/Controllers/ProfitAndLossReportController.php
  Modules/Report/Resources/views/finance/dashboard.blade.php
  Modules/Report/Resources/views/finance/profit-and-loss/detailed.blade.php
  Modules/Report/Resources/views/finance/profit-and-loss/index.blade.php
  Modules/Report/Routes/web.php
Labels: status : ready for review

#2547 Fixed wishlisted books functionality
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
Labels: status : ready for review

#2579 added modal to edit functionality
  Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
Labels: status : reviewed

#2589 feature/2588/mapping-between-domain-and-designations
  Modules/HR/Entities/HrJobDomain.php
  Modules/HR/Http/Controllers/HrJobDesignationController.php
  Modules/HR/Http/Requests/Recruitment/JobDesignationRequest.php
  Modules/HR/Services/HrJobDesignationService.php
  Modules/User/Resources/views/profile/show-basic-details.blade.php
  Modules/User/Services/ProfileService.php
  database/migrations/2022_10_10_164442_add_domain_id_to_hr_job_designation.php
  resources/js/app.js
  resources/views/hr/designations/edit.blade.php
  resources/views/hr/designations/index.blade.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#2503 all the fields visible on user profile
  Modules/User/Entities/User.php
  Modules/User/Http/Controllers/ProfileController.php
  Modules/User/Resources/assets/js/app.js
  Modules/User/Resources/views/profile/show-basic-details.blade.php
  Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
  database/migrations/2022_09_21_151439_rename_husband_name_in_user_profies_table.php
Labels: status : reviewed

#2598 Fixed year dropdown issue
  Modules/EffortTracking/Resources/views/show.blade.php
Labels: status : reviewed

#2528 Updated create form for expense
  Modules/Expense/Config/config.php
  Modules/Expense/Database/Migrations/2022_09_23_184506_create_expense_files_table.php
  Modules/Expense/Entities/ExpenseFile.php
  Modules/Expense/Http/Controllers/ExpenseController.php
  Modules/Expense/Resources/assets/js/app.js
  Modules/Expense/Resources/views/create.blade.php
  Modules/Expense/Resources/views/edit.blade.php
  Modules/Expense/Resources/views/index.blade.php
  Modules/Expense/Routes/web.php
  Modules/Expense/Services/ExpenseService.php
  Modules/Revenue/Resources/assets/js/app.js
  Modules/Revenue/Services/RevenueProceedService.php
Labels: status : ready for review

#2610 we need to show total number of book in knowledgeCafe module
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#2609 feature-2603-working-staff-directory
  Modules/HR/Config/config.php
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/User/Http/Controllers/UserSettingsController.php
  Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
  Modules/User/Resources/assets/js/components/UserListing.vue
  Modules/User/Resources/assets/js/vueComponents.js
  Modules/User/Resources/views/index.blade.php
  Modules/User/Resources/views/profile/show-basic-details.blade.php
  Modules/User/Routes/web.php
  database/migrations/2022_10_13_114321_add_staff_type_to_employees_table.php
  package-lock.json
  resources/views/hr/employees/index.blade.php
  resources/views/hr/employees/menu.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/settings/permissions/update-staff-type-modal.blade.php
  resources/views/settings/permissions/update-user-roles-modal.blade.php
  resources/views/settings/permissions/users.blade.php
Labels: status : ready for review, Development

#2614 create-search-bar
  Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
  resources/views/hr/job/index.blade.php
Labels: status : ready for review

#2630 Align the buttons in media module
  Modules/Media/Resources/views/media/show.blade.php
Labels: status : reviewed
