Repository ColoredCow/portal, pull requests merged in 2022-07, with the labels that each got.

#1671 Invoice UI fix
  Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1674 Only show active client invoices
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1703 Update information available in help icon when changing status of client from inactive to active
  Modules/Client/Resources/views/subviews/edit-client-details.blade.php
Labels: status : ready for review

#1705 color_changed in add client and search button
  Modules/Client/Resources/views/index.blade.php
Labels: status : reviewed

#1706 change view button theme and style
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#1700 Corrected casing of words on Monthly GST report page
  Modules/Invoice/Resources/views/monthly-gst-report.blade.php
Labels: status : ready for review

#1697 Fixed functionality to mark an application on hold and send an email to the candidate
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Emails/Recruitment/Applicant/OnHold.php
  Modules/HR/Entities/Application.php
  Modules/HR/Entities/ApplicationRound.php
  resources/views/hr/application/edit.blade.php
  resources/views/settings/hr/index.blade.php
  resources/views/settings/hr/on-hold.blade.php
Labels: status : reviewed

#1714 Applicant Email verification
  Modules/HR/Database/Migrations/2022_07_04_165601_add_verification_status_to_application.php
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
  Modules/HR/Listeners/Recruitment/AutoRespondApplicant.php
  Modules/HR/Providers/EventServiceProvider.php
  resources/sass/_variables.scss
  resources/views/hr/application/verification.blade.php
  resources/views/settings/hr/application-verification.blade.php
Labels: status : ready for review

#1702 Yearly invoice report
  Modules/Invoice/Config/config.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/views/invoice-report.blade.php
  Modules/Invoice/Resources/views/subviews/invoice-report/filters.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#1715 Email verification text updates
  resources/views/hr/application/verification.blade.php
Labels: status : ready for review

#1681 Fixed create seeders for Job opportunities in dev environment
  Modules/HR/Database/Factories/HrJobsFactory.php
  Modules/HR/Database/Seeders/HRDatabaseSeeder.php
  Modules/HR/Database/Seeders/HRJobsSeederTableSeeder.php
Labels: status : ready for review

#1727 Fix issue related to null project name
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/views/invoice-report.blade.php
  Modules/Invoice/Resources/views/subviews/invoice-report/filters.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1731 Updation in installation guidelines
  docs/installation.md
Labels: status : reviewed

#1738 Adding customization options like Paragraph,Font-Family,Font-sizes,etc
  resources/js/app.js
Labels: status : ready for review

#1739 Added pagination in Invoice Details
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1746 Increase scheduling frequency of sync after 4 hour
  app/Console/Kernel.php
Labels: status : ready for review

#1742 Contract file name is aligned in UI view
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
Labels: status : ready for review

#1755 change in dropdown menu
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#1753 Invoice reminder functionality
  Modules/Invoice/Config/config.php
  Modules/Invoice/Database/Migrations/2022_07_06_193708_add_mail_columns_to_invoices_table.php
  Modules/Invoice/Emails/SendInvoiceMail.php
  Modules/Invoice/Emails/SendPendingInvoiceMail.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/assets/js/app.js
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/mail/pending-invoice.blade.php
  Modules/Invoice/Resources/views/modals/invoice-email-preview.blade.php
  Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
  resources/views/settings/invoice/index.blade.php
  resources/views/settings/invoice/received-invoice-payment.blade.php
  resources/views/settings/invoice/send-invoice-reminder.blade.php
Labels: status : ready for review

#1756 change in text
  resources/views/layouts/navbar.blade.php
Labels: status : reviewed

#1690 add functionality for resources
  Modules/HR/Http/Controllers/ResourcesController.php
  Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/create-resources-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/index.blade.php
  Modules/HR/Resources/views/guidelines-resources/show.blade.php
  Modules/HR/Routes/web.php
  app/Models/Resource.php
  database/migrations/2022_06_27_122719_create_hr_resources_categories.php
  database/migrations/2022_06_28_054535_create_hr_resources_table.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#1766 Change invoice table email column type
  Modules/Invoice/Database/Migrations/2022_07_06_193708_add_mail_columns_to_invoices_table.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1730 Correctly aligned the UI of the dashboard
  resources/js/components/Dashboard/UserDashboardInfrastructure.vue
  resources/js/components/Dashboard/UserDashboardInvoice.vue
  resources/js/components/Dashboard/UserDashboardLibrary.vue
  resources/js/components/Dashboard/UserDashboardProjects.vue
  resources/sass/_variables.scss
  resources/views/home.blade.php
Labels: status : ready for review

#1780 Added the merge conflict references in the contribution.md
  docs/contributing.md
Labels: status : ready for review

#1782 Ready invoice not opening
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : ready for review

#1790 Feature/1583/add column
  Modules/Project/Resources/views/index.blade.php
Labels: status : ready for review

#1799 Replaced the js alert with bootstrap modal
  Modules/User/Resources/assets/js/components/UserListing.vue
Labels: status : ready for review, status : reviewed

#1802 Added a margin between book title and setting button
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : ready for review

#1791 Change in days calculation logic for different client billing dates
  Modules/Client/Entities/Client.php
  Modules/EffortTracking/Services/EffortTrackingService.php
  Modules/Project/Entities/Project.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/show.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#1801 change in color
  resources/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
  resources/views/knowledgecafe/library/books/update-category-modal.blade.php
  resources/views/knowledgecafe/library/categories/index.blade.php
Labels: status : ready for review

#1806 Disabled save button in add category popup on guidelines page
  Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
  resources/js/app.js
Labels: status : reviewed

#1729 Fixed need follow up tagged applications to be automatically reminded
  Modules/HR/Config/config.php
  Modules/HR/Console/Recruitment/MarkApplicationForFollowUp.php
  Modules/HR/Database/Seeders/SettingsTableSeeder.php
  Modules/HR/Events/FollowUpEvent.php
  Modules/HR/Listeners/FollowUpListener.php
  Modules/HR/Providers/EventServiceProvider.php
  resources/views/settings/hr/follow-up.blade.php
  resources/views/settings/hr/index.blade.php
Labels: status : reviewed

#1815 Fix issue related to modal not closing
  Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
Labels: status : reviewed

#1819 Fixed the Contibution guideline
  docs/contributing.md
Labels: status : reviewed

#1820 Parse invoice payment message
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1811 Yearly Invoice report export feature added
  Modules/Invoice/Exports/YearlyInvoiceReportExport.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/views/invoice-report.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1835 change type text to number
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: status : ready for review

#1840 Books category delete UI inconsistency
  resources/views/knowledgecafe/library/categories/index.blade.php
Labels: status : ready for review

#1842 Fixed title and input alignments
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#1781 over_flow_fix
  resources/views/knowledgecafe/library/books/show.blade.php
  resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
Labels: status : reviewed

#1852 All the headers Your wishlist,You have read,Recommended are alligned …
  resources/js/components/Dashboard/UserDashboardLibrary.vue
  resources/sass/app.scss
Labels: status : ready for review

#1850 Added new fields in invoice reminder email
  Modules/Invoice/Config/config.php
  Modules/Invoice/Emails/SendPendingInvoiceMail.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/assets/js/app.js
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : ready for review

#1859 Added invoice number and amount in received payment mail.
  Modules/Invoice/Config/config.php
  Modules/Invoice/Emails/SendPaymentReceivedMail.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1873 Updated color change and alignment fixed
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#1853 my profile ui alignment
  Modules/User/Resources/views/profile/show-basic-details.blade.php
Labels: status : ready for review, status : reviewed

#1872 team member efforts problem fixed.
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review

#1883 Close button is added
  Modules/HR/Resources/views/guidelines-resources/create-category-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/create-resources-modal.blade.php
Labels: status : ready for review

#1857 1818 channel for job applications
  Modules/HR/Database/Migrations/2022_07_15_115016_create_hr_channels_table.php
  Modules/HR/Database/Migrations/2022_07_15_115134_update_hr_applications_with_hr_channels_table.php
  Modules/HR/Database/Seeders/HRDatabaseSeeder.php
  Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
  Modules/HR/Entities/HrChannel.php
Labels: status : ready for review

#1874 Added Amount+GST, status columns and restructuring of data in yearly Invoice Report
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/invoice-report.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : reviewed

#1854 Added a refresh button to sync latest efforts for the projects in pro…
  Modules/EffortTracking/Http/Controllers/EffortTrackingController.php
  Modules/EffortTracking/Resources/assets/js/app.js
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/EffortTracking/Routes/api.php
  Modules/EffortTracking/Services/EffortTrackingService.php
  Modules/Project/Console/SyncEffortsheet.php
  Modules/User/Entities/User.php
Labels: status : ready for review

#1887 Update receive payment confirmation message
  Modules/Invoice/Config/config.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review

#1891 Hours booked,Expected Hours and velocity column are alligned properly…
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#1881 bugfix_when_clicking_on_view_button_avilable_in_analytics.
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
Labels: status : reviewed

#1834 Modified the send confirmation mail functionality
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: status : reviewed

#1860 headers issue is resolved
  Modules/Client/Resources/views/index.blade.php
  Modules/HR/Resources/views/tags/index.blade.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/invoice-report.blade.php
  Modules/Invoice/Resources/views/monthly-gst-report.blade.php
  Modules/Invoice/Resources/views/tax-report.blade.php
  Modules/Prospect/Resources/views/index.blade.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/volunteer/index.blade.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#1889 Feature/Profit and Loss Report
  Modules/Invoice/Console/FixInvoiceAmountsCommand.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Providers/InvoiceServiceProvider.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Report/Config/config.php
  Modules/Report/Http/Controllers/FinanceReportController.php
  Modules/Report/Resources/views/finance/profit-and-loss.blade.php
  Modules/Report/Routes/web.php
  Modules/Report/Services/Finance/ExpensesReportService.php
  Modules/Report/Services/Finance/ProfitAndLossReportService.php
  Modules/Report/Services/Finance/RevenueReportService.php
  resources/views/layouts/navbar.blade.php
Labels: status : reviewed

#1897 Added a "Last refreshed at" feature to the Project details page
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/EffortTracking/Services/EffortTrackingService.php
Labels: status : ready for review

#1864 add the label and fix the font
  Modules/Project/Resources/views/index.blade.php
Labels: status : ready for review

#1893 Added 6sec timer to alert
  Modules/Invoice/Resources/assets/js/app.js
Labels: status : reviewed

#1907 Automation/add channles through UI
  Modules/HR/Http/Controllers/HrChannelController.php
  Modules/HR/Routes/web.php
  resources/views/hr/application/create.blade.php
Labels: status : reviewed

#1912 Round review bug resolved
  resources/views/hr/application/edit.blade.php
Labels: status : ready for review

#1904 Bugfix limited team members
  Modules/Project/Resources/views/index.blade.php
Labels: status : ready for review

#1921 Evaluation round mapped
  Modules/HR/Http/Controllers/EvaluationController.php
  Modules/HR/Resources/views/evaluation/segment/create.blade.php
Labels: status : ready for review

#1792 add domain button
  Modules/HR/Database/Migrations/2022_07_07_075310_create_hr_job_domains_table.php
  Modules/HR/Database/Seeders/DomainTableSeeder.php
  Modules/HR/Entities/HrJobDomain.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Http/Requests/Recruitment/JobDomainRequest.php
  Modules/HR/Routes/web.php
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: status : reviewed

#1841 Fix/1571/count of application new
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  resources/views/hr/application/index.blade.php
  resources/views/hr/application/total-application-count-modal.blade.php
  resources/views/hr/menu.blade.php
Labels: status : ready for review, status : reviewed

#1879 sort clients by name
  Modules/Project/Services/ProjectService.php
Labels: status : reviewed

#1838 opportunity id problem solved
  resources/js/app.js
  resources/views/hr/application/create.blade.php
Labels: status : ready for review

#1932 limited team members
  resources/sass/_variables.scss
Labels: status : ready for review

#1936 Replace books count JS alert with modal form
  resources/js/app.js
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : ready for review

#1916 added client column to invoice records
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : ready for review

#1886 send email to non verified applicants
  .env.example
  Modules/HR/Config/config.php
  Modules/HR/Console/Recruitment/DailyMessage.php
  Modules/HR/Providers/HRServiceProvider.php
  app/Console/Kernel.php
  app/Mail/sendEmail.php
  resources/views/emails/send-non-verified-applicants-information-email.blade.php
Labels: status : reviewed

#1926 1920-fixing-allignment-of-effortsheet-and-status-button
  Modules/Project/Resources/views/show.blade.php
Labels: status : reviewed

#1884 Basic salary details page for employees
  .github/workflows/coding-standards.yml
  Modules/HR/Entities/Employee.php
  Modules/Salary/Database/Migrations/2022_07_17_103448_create_employee_salaries_table.php
  Modules/Salary/Database/Seeders/SalaryPermissionTableSeeder.php
  Modules/Salary/Entities/EmployeeSalary.php
  Modules/Salary/Http/Controllers/SalaryController.php
  Modules/Salary/Policies/EmployeeSalaryPolicy.php
  Modules/Salary/Providers/SalaryServiceProvider.php
  Modules/Salary/Resources/views/employee/index.blade.php
  Modules/Salary/Routes/web.php
  resources/views/hr/employees/show.blade.php
  resources/views/hr/employees/sub-views/menu.blade.php
Labels: status : ready for review

#1894 Feature/1772/fixing new status
  Modules/HR/Entities/ApplicationRound.php
Labels: status : ready for review, status : reviewed

#1945 Bugfix/1825 knowledge cafe not accessable
  resources/views/knowledgecafe/library/categories/index.blade.php
Labels: status : reviewed

#1955 Bugfix/1828/the error is dispayed on screen when clicking on view button available in analytics
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
Labels: status : ready for review

#1967 fix(package-lock): fixed conflicts in package lock file
  package-lock.json
Labels: priority : high !!

#1965 Created a div to make all the text and icon color identical in the menu
  resources/views/hr/menu.blade.php
Labels: status : ready for review

#1918 Replace-edit-button-with-edit-icon
  Modules/HR/Resources/views/evaluation/index.blade.php
Labels: status : ready for review

#1914 created Secondary Billing contact, Tertiary billing contact roles in edit client information page for storing clients Emails
  Modules/Client/Config/config.php
  Modules/Client/Entities/Client.php
  Modules/Client/Resources/views/subviews/edit-client-contact-persons.blade.php
  Modules/Invoice/Resources/assets/js/app.js
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/modals/invoice-email-preview.blade.php
  Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
  Modules/Invoice/Resources/views/modals/payment-received.blade.php
Labels: status : reviewed

#1970 changes done for production
  resources/views/knowledgecafe/library/books/update-category-modal.blade.php
Labels: status : ready for review

#1968 Employee salary page UI fixes
  Modules/HR/Entities/Employee.php
  Modules/Salary/Database/Seeders/SalaryPermissionTableSeeder.php
  Modules/Salary/Resources/views/employee/index.blade.php
  resources/views/hr/employees/sub-views/menu.blade.php
Labels: status : reviewed

#1982 Some Changes are done in total count
  resources/views/hr/menu.blade.php
Labels: status : ready for review

#1972 1931-In-employee-page-highlighting-the-FTE-with-correct-colour
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#1984 Project Level Invoice Generation
  .env.example
  Modules/Client/Entities/Client.php
  Modules/EffortTracking/Services/EffortTrackingService.php
  Modules/Invoice/Emails/SendInvoiceMail.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/assets/js/app.js
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/modals/invoice-email-preview.blade.php
  Modules/Invoice/Resources/views/modals/payment-received.blade.php
  Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
  Modules/Invoice/Resources/views/render/render.blade.php
  Modules/Invoice/Resources/views/subviews/invoice-report/invoice-details-modal.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Entities/Project.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Services/ProjectService.php
  config/app.php
Labels: status : ready for review

#1983 UI issue of the pages in HR module has been solved
  Modules/HR/Resources/views/tags/index.blade.php
  Modules/HR/Resources/views/universities/index.blade.php
  resources/views/hr/application/volunteer/index.blade.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#1923 add edit and delete functionality for HR resource
  Modules/HR/Entities/Job.php
  Modules/HR/Http/Controllers/ResourcesController.php
  Modules/HR/Resources/assets/js/app.js
  Modules/HR/Resources/views/guidelines-resources/edit-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/hr-category-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/hr-resources-modal.blade.php
  Modules/HR/Resources/views/guidelines-resources/show.blade.php
  Modules/HR/Routes/web.php
  app/Models/Resource.php
  resources/js/app.js
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#1985 Displayed my project by default
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#1892 Showing the team members in halted project
  Modules/Project/Services/ProjectService.php
Labels: status : reviewed

#1993 made-phone no field alphanumeric
  Modules/Client/Resources/views/subviews/edit-client-contact-persons.blade.php
Labels: status : reviewed

#1999 changed the format of date and time
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#1996 all projects listing page only when clicking on All projects
  Modules/EffortTracking/Resources/views/show.blade.php
Labels: status : ready for review

#1975 Feature/render the data of invoice mails table in UI
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/edit.blade.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/modals/email-details.blade.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : ready for review, status : reviewed

#1963 Feature/store emails in invoice mails table
  Modules/Invoice/Config/config.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/edit.blade.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/modals/email-details.blade.php
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
Labels: status : reviewed

#2002 Display client name in project details page
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#2007 Resolved error
  Modules/Client/Http/Requests/ClientFormsRequest.php
Labels: status : ready for review

#2009 Corrected the format
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#1994 team member image highlighted
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Resources/views/show.blade.php
  resources/sass/app.scss
  resources/views/project/edit.blade.php
  resources/views/project/show.blade.php
Labels: status : reviewed

#2000 Employee salary breakdown using salary setting page data
  Modules/Salary/Config/config.php
  Modules/Salary/Database/Seeders/SalaryPermissionTableSeeder.php
  Modules/Salary/Entities/SalaryConfiguration.php
  Modules/Salary/Http/Controllers/SalaryController.php
  Modules/Salary/Http/Controllers/SalarySettingController.php
  Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
  Modules/Salary/Resources/assets/js/vueComponents.js
  Modules/Salary/Resources/views/employee/index.blade.php
  Modules/Salary/Resources/views/settings/index.blade.php
  Modules/Salary/Routes/web.php
  resources/js/app.js
  resources/views/settings/index.blade.php
Labels: status : ready for review

#2015 Faker locale to IN
  config/app.php
Labels: status : ready for review

#2019 #1970 CI fixes
  Modules/Salary/Http/Controllers/SalarySettingController.php
  Modules/Salary/Http/Requests/SalarySettingRequest.php
Labels: status : ready for review

#2021 Vue toast notification
  Modules/Client/Resources/views/index.blade.php
  Modules/EffortTracking/Resources/assets/js/app.js
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/modal-success.blade.php
  Modules/Salary/Resources/views/settings/index.blade.php
  Modules/User/Resources/assets/js/components/RoleListing.vue
  package-lock.json
  package.json
  resources/js/app.js
  resources/sass/app.scss
  resources/views/toast.blade.php
Labels: status : reviewed

#2010 1991-removing-error-displayed-in-NDA-template
  resources/views/settings/agreement/nda/index.blade.php
Labels: status : ready for review, status : reviewed

#2025 Client policy fixes
  Modules/Client/Policies/ClientPolicy.php
Labels: status : ready for review

#2036 2006/pagination project listening page
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#2032 image icon should be available under the key account manager and On h…
  Modules/Client/Resources/views/subviews/listing-client-row.blade.php
Labels: status : ready for review

#2046 Fix - Project edit page not opening
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#2037 Full salary breakdown
  Modules/Salary/Config/config.php
  Modules/Salary/Http/Requests/SalarySettingRequest.php
  Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
  Modules/Salary/Resources/views/settings/index.blade.php
Labels: status : reviewed

#2048 Fix/1773/sort by filter in hr applications listing
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#1843 1760 verified applications
  Modules/HR/Http/Controllers/Recruitment/ReportsController.php
  resources/js/app.js
  resources/views/hr/recruitment/reports.blade.php
Labels: status : ready for review

#2057 Fix replaced nan with zero
  Modules/Salary/Resources/assets/js/components/SalaryBreakdown.vue
Labels: status : reviewed

#2062 fix(job-application-listing): listing sorted by scheduled person id
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  resources/views/hr/application/index.blade.php
Labels: priority : critical !!!, module : hr

#2059 Cleanups on Infrastructure pages
  Modules/Infrastructure/Config/config.php
  Modules/Infrastructure/Http/Controllers/InfrastructureController.php
  Modules/Infrastructure/Resources/views/ec2-instances.blade.php
  Modules/Infrastructure/Resources/views/index.blade.php
  Modules/Infrastructure/Resources/views/instances.blade.php
  Modules/Infrastructure/Resources/views/menu_header.blade.php
  Modules/Infrastructure/Resources/views/s3-buckets.blade.php
  Modules/Infrastructure/Routes/web.php
  Modules/Infrastructure/Services/InfrastructureService.php
  resources/js/components/Dashboard/UserDashboardInfrastructure.vue
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2068 Toast message added
  Modules/User/Resources/assets/js/components/UpdateRolePermissionModal.vue
  Modules/User/Resources/assets/js/components/UpdateUserRoleModal.vue
  Modules/User/Resources/assets/js/components/UserListing.vue
  Modules/User/Resources/views/index.blade.php
  Modules/User/Resources/views/roles/index.blade.php
Labels: status : ready for review

#2069 New custom invoice template for a client
  Modules/Client/Config/config.php
  Modules/Client/Entities/Client.php
  Modules/Client/Resources/views/index.blade.php
  Modules/Client/Resources/views/subviews/edit-client-billing-details.blade.php
  Modules/Invoice/Config/config.php
  Modules/Invoice/Database/Migrations/2022_07_28_072352_create_ledger_accounts_table.php
  Modules/Invoice/Entities/LedgerAccount.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/ledger-accounts/index.blade.php
  Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
  Modules/Invoice/Resources/views/render/invoice-template.blade.php
  Modules/Invoice/Resources/views/render/resource-based-billing-template.blade.php
  Modules/Invoice/Routes/web.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Database/Migrations/2022_07_28_094606_add_billing_engagement_column_to_project_team_member_table.php
  Modules/Project/Entities/Project.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
  Modules/Project/Services/ProjectService.php
  app/Casts/Decrypted.php
  app/Helpers/DecimalToWordsHelper.php
  app/Traits/Encryptable.php
  config/constants.php
  resources/views/layouts/navbar.blade.php
Labels: status : reviewed

#2071 Added new env variables for custom invoices
  .env.example
Labels: status : ready for review

#2072 Permissions policies fixes
  Modules/Client/Database/Factories/ClientFactory.php
  Modules/Client/Database/Seeders/ClientDatabaseSeeder.php
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Policies/EmployeePolicy.php
  Modules/HR/Providers/HRAuthServiceProvider.php
  Modules/HR/Routes/web.php
  Modules/Invoice/Http/Controllers/InvoiceController.php
  Modules/Invoice/Policies/InvoicePolicy.php
  Modules/Invoice/Providers/InvoiceAuthServiceProvider.php
  Modules/Invoice/Providers/InvoiceServiceProvider.php
  Modules/Invoice/Routes/web.php
  Modules/Report/Http/Controllers/FinanceReportController.php
  Modules/User/Database/Seeders/UserDatabaseSeeder.php
  app/Http/Controllers/HR/Employees/ReportsController.php
  database/factories/ClientFactory.php
  database/migrations/2018_10_23_202033_create_employee_project_table.php
  routes/web.php
Labels: status : reviewed

#2044 Fixed the overflow of contract file name
  Modules/Project/Resources/views/subviews/create-project-details.blade.php
Labels: status : ready for review

#2063 changed the format of date and time
  Modules/EffortTracking/Resources/views/show.blade.php
  Modules/Project/Resources/views/show.blade.php
Labels: status : ready for review

#2061 Addition of start date and End date field
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : reviewed

#2053 add job domaim form validations
  Modules/HR/Http/Requests/Recruitment/JobDomainRequest.php
  resources/js/app.js
  resources/views/hr/job/create.blade.php
Labels: status : reviewed

#2077 Calculate billable amount of project based on resource
  Modules/Client/Entities/Client.php
  Modules/Invoice/Resources/views/index.blade.php
  Modules/Invoice/Resources/views/ledger-accounts/index.blade.php
  Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Database/Migrations/2022_07_31_005331_create_project_billing_details_table.php
  Modules/Project/Database/Migrations/2022_07_31_173825_update_started_on_column_to_nullable_in_project_team_members_table.php
  Modules/Project/Entities/Project.php
  Modules/Project/Entities/ProjectBillingDetail.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/edit-project-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-financial-details.blade.php
  Modules/Project/Resources/views/subviews/edit-project-repository.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
  Modules/Project/Services/ProjectService.php
  config/database.php
Labels: status : ready for review

#2079 Fixes in the custom invoice
  Modules/Invoice/Resources/views/render/custom-invoice-template-1.blade.php
  Modules/Project/Resources/assets/js/app.js
  Modules/Project/Resources/views/edit.blade.php
  Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
Labels: status : ready for review
