Repository ColoredCow/portal, pull requests merged in 2022-11, with the labels that each got.

#2634 number of people in the team
  Modules/Project/Resources/views/show.blade.php
Labels: status : reviewed

#2637 Added the search bar and sorted on the basis maximum project first
  Modules/HR/Http/Controllers/EmployeeController.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready for review

#2601 email template
  Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
Labels: status : ready for review, status : reviewed

#2606 update feedback and schedule
  Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
Labels: status : ready for review

#2644 designation and requisition permission permission for HR-Manager
  Modules/HR/Database/Seeders/HRPermissionsTableSeeder.php
  Modules/HR/Policies/HrJobDesignationPolicy.php
  Modules/HR/Policies/JobRequisitionPolicy.php
  Modules/HR/Providers/HRAuthServiceProvider.php
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#2643 Added a search bar on the HR designations page
  Modules/HR/Http/Controllers/HrJobDesignationController.php
  Modules/HR/Services/HrJobDesignationService.php
  resources/views/hr/designations/index.blade.php
Labels: status : ready for review
