Repository ColoredCow/portal, pull requests merged in 2023-06, with the labels that each got.

#3112 sending data to campaigns
  .env.example
  Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
  Modules/HR/Services/ApplicationService.php
  config/constants.php
Labels: status : ready for review

#3116 Created a new laravel console command
  app/Console/Commands/sendNewSubscriber.php
Labels: status : ready for review

#3124 Feature/3114/create laravel console command for new subscriber
  Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
  Modules/HR/Services/ApplicationService.php
  app/Console/Commands/sendNewSubscriber.php
Labels: status : ready for review

#3126 #3031 Added clear button in Project Resouce Page
  Modules/Project/Resources/views/resource-requirement.blade.php
Labels: status : ready for review

#3120 Applied `Month and Year` filters for Employee FTE-Report.
  Modules/HR/Entities/Employee.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Resources/views/index.blade.php
  Modules/Project/Resources/views/subviews/excel-download-filters.blade.php
  Modules/Project/Routes/web.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#3130 #3129 Display Only Active Applicants in CodeTreak Applicant Sidebar and Resolve Overlapping with Other Modules.
  app/Http/View/Composers/CodeTrekApplicantsComposer.php
  resources/sass/app.scss
Labels: status : ready for review

#3141 Refactored monthly sales register report excel
  Modules/Client/Entities/ClientAddress.php
  Modules/Report/Exports/MonthlySalesRegisterReportExport.php
  Modules/Report/Http/Controllers/MonthlySalesRegisterController.php
  Modules/Report/Resources/views/finance/dashboard.blade.php
  Modules/Report/Resources/views/finance/monthly-sales-register/filters.blade.php
  Modules/Report/Resources/views/finance/monthly-sales-register/index.blade.php
  Modules/Report/Routes/web.php
  Modules/Report/Services/Finance/MonthlSalesRegisterService.php
Labels: status : ready for review

#3140 Update the version of Node.jd and NPM
  package.json
Labels: status : ready for review

#3138 Remove the laravel command
  app/Console/Commands/sendNewSubscriber.php
Labels: status : ready for review

#3147 Saving campaign token in cache
  Modules/HR/Services/ApplicationService.php
Labels: status : ready for review

#3082 rename round name from round_name to current_round_name in code_trek_…
  Modules/CodeTrek/Resources/views/evaluate.blade.php
  Modules/CodeTrek/Resources/views/index.blade.php
  Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
  Modules/CodeTrek/Services/CodeTrekService.php
  database/migrations/2023_05_17_114304_rename_round_name_column_of_code_trek_applicants_table.php
  database/migrations/2023_05_18_162751_rename_round_name_column_of_codetrek_applicant_round_details_table.php
Labels: status : ready for review

#3090 Send mail to applicant
  Modules/CodeTrek/Emails/CodetrekMailApplicant.php
  Modules/CodeTrek/Resources/views/mail/codetrek.blade.php
  Modules/CodeTrek/Services/CodeTrekService.php
Labels: status : reviewed

#3163 Fixes for Project-fte-report and Monthly-sales-register-report
  Modules/HR/Entities/Employee.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Exports/ProjectFTEExport.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/subviews/excel-download-filters.blade.php
  Modules/Project/Services/ProjectService.php
  Modules/Report/Resources/views/finance/monthly-sales-register/filters.blade.php
Labels: status : ready for review

#3175 #3164 Remove the inactive team members and inactive or halted projects from email notification
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#3181 Fixed the bug for employee working staff
  Modules/HR/Http/Controllers/EmployeeController.php
Labels: status : ready for review

#3188 Release June 22
  Modules/CodeTrek/Emails/CodetrekMailApplicant.php
  Modules/CodeTrek/Resources/views/evaluate.blade.php
  Modules/CodeTrek/Resources/views/index.blade.php
  Modules/CodeTrek/Resources/views/mail/codetrek.blade.php
  Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
  Modules/CodeTrek/Services/CodeTrekService.php
  Modules/HR/Entities/Employee.php
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Services/ApplicationService.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/Project/Exports/ProjectFTEExport.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/subviews/excel-download-filters.blade.php
  Modules/Project/Services/ProjectService.php
  Modules/Report/Resources/views/finance/monthly-sales-register/filters.blade.php
  app/Console/Commands/sendNewSubscriber.php
  database/migrations/2023_05_17_114304_rename_round_name_column_of_code_trek_applicants_table.php
  database/migrations/2023_05_18_162751_rename_round_name_column_of_codetrek_applicant_round_details_table.php
Labels: status : ready for review

#3172 issue/#3027/Books counts are not shown properly
  app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
  app/Http/Controllers/KnowledgeCafe/Library/BookController.php
  resources/views/knowledgecafe/library/menu.blade.php
Labels: status : reviewed

#3056 Changed the implementation of new Sales Area page to modal form in bo…
  Modules/SalesAutomation/Http/Controllers/SalesAreaController.php
  Modules/SalesAutomation/Resources/views/sales-area/create.blade.php
  Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
  public/images/no-result.png
  resources/views/layouts/app.blade.php
Labels: status : reviewed

#3180 Slow loading of HR recruitment page on the Portal
  Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
  resources/views/hr/application/index.blade.php
Labels: type : bug 🐛

#3190 #2823 Show Project Velocity in dashboard
  Modules/Project/Entities/Project.php
  resources/js/components/Dashboard/UserDashboardProjects.vue
Labels: status : ready for review

#3189 fix the media close button alignment issue
  Modules/Media/Resources/views/media/index.blade.php
Labels: status : ready for review

#3203 Add-toast-message-when-user-give-feedback-to-codetrek-applicant
  Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
Labels: status : ready for review

#3161 updated the installlation guide
  docs/installation.md
  docs/prerequisites.md
Labels: status : reviewed

#3134 #3023 Add Counts to each tabs in CodeTrek
  Modules/CodeTrek/Http/Controllers/CodeTrekController.php
  Modules/CodeTrek/Resources/views/index.blade.php
  Modules/CodeTrek/Services/CodeTrekService.php
Labels: status : ready for review

#3155 Show project to KeyAccountManger
  Modules/Project/Entities/Project.php
  Modules/Project/Resources/views/index.blade.php
Labels: status : ready for review

#3132 Update the CodeTrek installation guide line
  docs/installation.md
Labels: status : ready for review

#3127 Fix User Permissions Handling for CodeTrek Module
  Modules/CodeTrek/Http/Controllers/CodeTrekController.php
  Modules/CodeTrek/Policies/CodetrekApplicantPolicy.php
  Modules/CodeTrek/Resources/views/index.blade.php
  Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
Labels: status : ready for review

#2949 feature/2929/add-requisition-button-functionality-to-project-resource-page
  Modules/HR/Entities/JobRequisition.php
  Modules/HR/Http/Controllers/RequisitionController.php
  Modules/HR/Jobs/SendHiringMailJob.php
  Modules/Project/Http/Controllers/ProjectController.php
  Modules/Project/Resources/views/resource-requirement.blade.php
  database/migrations/2023_04_14_125207_add_requested_by_to_job_requisition.php
  resources/js/app.js
  resources/views/hr/employees/fte-handler.blade.php
  resources/views/hr/requisition/index.blade.php
Labels: status : ready for review

#3012 bugfix/Updated_Status_message_is_not_shown
  Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
Labels: status : ready for review

#2998 make the invoice page responsive
  Modules/Invoice/Resources/views/index-filters.blade.php
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : ready for review

#3085 Added new columns, new tooltips and fixed FTE calculation on user dashboard page
  Modules/Report/Resources/assets/js/app.js
  Modules/Report/Services/User/UserReportService.php
  resources/views/hr/employees/show.blade.php
  resources/views/settings/bank-details.blade.php
Labels: status : ready for review

#3208 #3206 Fix: Adding 'Mark Active' Button in Applicants List for Resolving Inactive User Issue
  Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
  Modules/CodeTrek/Resources/views/evaluate.blade.php
Labels: status : ready for review

#3209 Remove the inactive users #3205
  Modules/User/Services/UserService.php
Labels: status : reviewed

#3101 Implement email notification for applicant round changes
  Modules/CodeTrek/Emails/CodeTrekApplicantRoundMail.php
  Modules/CodeTrek/Resources/views/mail/codetrek-round.blade.php
  Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
Labels: status : reviewed

#3174 Automated review system
  Modules/HR/Console/QuarterlyReviewSystemForEmployee.php
  Modules/HR/Entities/Employee.php
  Modules/HR/Http/Controllers/EmployeeController.php
  app/Console/Kernel.php
  config/constants.php
  resources/views/hr/employees/index.blade.php
Labels: status : reviewed

#3217 Commented Some Lines
  Modules/CodeTrek/Http/Controllers/CodeTrekController.php
Labels: status : ready for review
