Repository ColoredCow/portal, pull requests merged in 2023-05, with the labels that each got.

#3055 Add Preparatory in codetrek module
  Modules/CodeTrek/Config/config.php
Labels: status : reviewed, Module:CodeTrek

#3053 make the query to search the applicants by their full name
  Modules/CodeTrek/Resources/views/index.blade.php
  Modules/CodeTrek/Services/CodeTrekService.php
Labels: status : ready for review

#2977 office location phase 2
  Modules/Operations/Entities/OfficeLocation.php
  Modules/Operations/Http/Controllers/OperationsController.php
  Modules/Operations/Resources/views/modals/add-center-modal.blade.php
  Modules/Operations/Resources/views/office-location/index.blade.php
  Modules/Operations/Routes/web.php
  Modules/Operations/Services/OperationService.php
  database/migrations/2023_04_17_113950_create_office_locations_table.php
Labels: status : ready for review, module: operations

#3064 Make the client page responsive
  Modules/Client/Resources/views/index.blade.php
  Modules/Client/Resources/views/subviews/listing-client-row.blade.php
Labels: status : reviewed

#2517 Bugfix/updated required changes
  docs/RighSide.png
  docs/assign-label.png
  docs/assign-reviewers.png
  docs/assign-yourself.png
  docs/contributing.md
Labels: status : ready for review

#2666 adding search icon
  resources/views/knowledgecafe/library/books/index.blade.php
Labels: status : reviewed

#3070 Make the HR recruitment page responsive
  resources/views/hr/application/index.blade.php
Labels: status : reviewed

#3072 Change the status with applicant level
  Modules/CodeTrek/Config/config.php
  Modules/CodeTrek/Resources/views/index.blade.php
Labels: status : reviewed

#3043 Feature/3017 activate edit and delete icons
  Modules/Operations/Http/Controllers/OperationsController.php
  Modules/Operations/Resources/views/office-location/edit.blade.php
  Modules/Operations/Resources/views/office-location/index.blade.php
  Modules/Operations/Routes/web.php
  Modules/Operations/Services/OperationService.php
Labels: status : reviewed, module: operations

#3077 Update installation.md
  docs/installation.md
Labels: status : ready for review

#3036 Feature/3020/creating seeder
  Modules/CodeTrek/Database/Factories/.gitkeep
  Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
  Modules/CodeTrek/Database/Factories/CodeTrekApplicantRoundDetailFactory.php
  Modules/CodeTrek/Database/Seeders/CodeTrekApplicantsTableSeeder.php
  Modules/CodeTrek/Database/Seeders/CodeTrekDatabaseSeeder.php
  Modules/CodeTrek/Entities/CodeTrekApplicant.php
  Modules/CodeTrek/Entities/CodeTrekApplicantRoundDetail.php
Labels: status : reviewed

#3086 Show clients status count on menu header
  Modules/Client/Resources/views/index.blade.php
  Modules/Client/Resources/views/menu_header.blade.php
  Modules/Client/Services/ClientService.php
Labels: status : reviewed

#3102 bugfix/ fix application no show email as it was inserting with the same data
  Modules/HR/Console/Recruitment/ApplicationNoShow.php
Labels: status : ready for review

#3081 Send list of expired jobs to hr
  Modules/HR/Console/JobExpiredEmailToHr.php
  Modules/HR/Emails/SendJobExpiredMail.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  app/Console/Kernel.php
  resources/views/emails/send-job-expired-mail.blade.php
Labels: status : ready for review

#3107 Display Designations in Resource Required Column on Project Resource …
  Modules/Project/Resources/views/resource-requirement.blade.php
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#3106 Fixed project Count not shown properly in CRM Module
  Modules/Project/Services/ProjectService.php
Labels: status : ready for review

#3091 Add-Dropdown-on-Dashboard
  Modules/User/Entities/User.php
  app/Http/Controllers/HomeController.php
  resources/views/home.blade.php
  routes/web.php
Labels: status : reviewed, module: operations
