Repository ColoredCow/portal, pull requests merged in 2024-03, with the labels that each got.

#3438 #3411/Add Client PAN number in our invoices
  Modules/Invoice/Resources/views/render/invoice-template.blade.php
Labels: status : ready for review

#3439 Bugfix/pan field conditional rendering
  Modules/Invoice/Resources/views/render/invoice-template.blade.php
Labels: status : ready to deploy

#3442 #3441 - Hide non-billable projects and clients
  Modules/Client/Entities/Client.php
  Modules/Client/Resources/views/subviews/create-client-details.blade.php
  Modules/Client/Resources/views/subviews/edit-client-details.blade.php
  Modules/Client/Services/ClientService.php
  Modules/Invoice/Entities/Invoice.php
  Modules/Invoice/Resources/views/subviews/create/custom-invoice.blade.php
  Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
  Modules/Invoice/Services/InvoiceService.php
  Modules/Project/Config/config.php
  Modules/Project/Entities/Project.php
  Modules/Project/Http/Requests/ProjectRequest.php
  database/migrations/2024_03_02_122211_add_is_billable_column_to_client_table.php
Labels: status : ready for review

#3447 #3445 - Navigation fixes
  resources/views/layouts/navbar.blade.php
Labels: status : ready for review

#3450 Job titles in emails
  resources/views/mail/hr/interviewer-scheduled-rounds-reminder.blade.php
Labels: status : ready for review

#3449 #3445 - Active project count & previous employee dashboard fixes
  Modules/HR/Http/Controllers/EmployeeController.php
  Modules/HR/Observers/EmployeeObserver.php
  Modules/Report/Http/Controllers/UserReportController.php
  Modules/Report/Routes/web.php
  Modules/User/Http/Controllers/ProfileController.php
  Modules/User/Routes/web.php
  app/Services/EmployeeService.php
  resources/views/hr/employees/basic-details.blade.php
  resources/views/hr/employees/index.blade.php
  resources/views/hr/employees/show.blade.php
Labels: status : ready for review

#3452 Feedback implementation in Finance Module
  Modules/Client/Resources/views/subviews/edit-client-billing-details.blade.php
  Modules/Invoice/Resources/views/index.blade.php
Labels: status : ready for review

#3456 #3458 Display total fte of the employee
  Modules/Project/Entities/Project.php
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/User/Entities/User.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready to test

#3459 #3456 - UI fixes at employee listing screen
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/User/Entities/User.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready to test

#3460 #3456 - Employees listing UI fixes
  Modules/Project/Entities/ProjectTeamMember.php
  Modules/User/Entities/User.php
  resources/views/hr/employees/index.blade.php
Labels: status : ready to test

#3463 #3462 Fix job application and creation workflow.
  Modules/HR/Config/config.php
  Modules/HR/Observers/Recruitment/JobObserver.php
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: status : ready for review

#3470 #3469 Fixed the issue of numbers with comma was not getting parsed.
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: priority : critical !!!

#3475 #3474 Fix message string parsing issue.
  Modules/HR/Resources/views/application/render-application-row.blade.php
Labels: status : ready for review

#3484 #3483 Decimal value rounding in the client conversion rate.
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: priority : critical !!!

#3485 #3483 Decimal value rounding in the client conversion rate.
  Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
Labels: Development

#3488 Fixed the logic to show user basic details
  Modules/HR/Database/Factories/HrEmployeeFactory.php
  Modules/HR/Entities/Employee.php
  Modules/HR/Entities/HrJobDesignation.php
  Modules/User/Http/Controllers/ProfileController.php
  Modules/User/Resources/views/profile/show-basic-details.blade.php
  Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
  database/migrations/2024_03_20_154825_drop_column_domain_id_from_table_employee.php
  resources/views/hr/designations/edit.blade.php
  resources/views/hr/employees/show.blade.php
Labels: status : ready for review
